### ISSUE TITLE
Missing logrotation

### ISSUE THREAD

**Issue by Rendanic** [oravirt/ansible-oracle#12]
I added a logrotate template for all files from ADR which were not cleaned up by ADR.
I also plan another cron for the ADR-stuff for a completed rotation of all logfiles.

I am not sure when the 2nd part is finished as I need a real working ADR flush, which was not easy the old days with different versions of Oracle on 1 host and never tested it again. Normaly I only remove the XML-files with find and not using the automatic stuff from ADR anymore.

Which path should we go?
The expected way from Oracle or the easy way with find?

**Comment by oravirt** [comment]
Just use find, I always do that.

**Comment by oravirt** [comment]
One thing though, make this a separate role. That will make it easy to use across both gi & db

**Comment by oravirt** [comment]
I just realized that I have a role that does this. I'll push that up and maybe we can use that as a base?
It's a simple role that manages logrotate and cron
