### ISSUE TITLE
[oradb-manage-db giving this error. Any suggestions?

### ISSUE THREAD

**Issue by asb2018** [oravirt/ansible-oracle#120]
TASK [oradb-manage-db : include_tasks] **********************************************************************************************************************
fatal: [vlt-dbatest1.dhe.duke.edu]: FAILED! => {"reason": "no action detected in task. This often indicates a misspelled module name, or incorrect module pat                                                                                h.\n\nThe error appears to have been in '/u01/playbook1/ansible-oracle-master/roles/oradb-manage-db/tasks/manage-db.yml': line 71, column 3, but may\nbe else                                                                                where in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: manage-db | create/manage database\n  ^ here\n"}

**Comment by oravirt** [comment]
Hi,
You're most likely missing the modules in the `library` folder. 
I'm not sure how you cloned the repo, but you need to add the `--recursive` to the '`git clone`' command.
e.g
`git clone --recursive https://github.com/oravirt/ansible-oracle`

or, you can also do this:
`git submodule init`
`git submodule update`
