### ISSUE TITLE
HugePages <> memory_target

### ISSUE THREAD

**Issue by Rendanic** [oravirt/ansible-oracle#13]
My installations are creating databases with memory_target which means that Oracle is unable to use HugePages, which is fine in small environments with less processes.

The current way for setting the hugepages in percent of RAM is not a good idea, because it is hard to define a good limit in systems with big memory. I prefer a solution with a fixed value of number of hugepages or a memory size which will be calculated to the right number of pages.

Any wish how we could solve this? I could implement it but like to know how it should be implemented in ansible-oracle.

The last step is the correction for real usage of HugePages while creating the database which is a 2nd part of this problem.

**Comment by oravirt** [comment]
I don't really see the problem with this (or maybe I dont understand what you mean).
Does it matter if you specify HP as a percentage of RAM or set it as a fixed size? You still need to do the hugepages/sga math and will end up with the same number of HP.
And defining a limit on systems with big memory is something you still have to do, regardless of if you calculate by percent or not.
If I say "use 256GB" for hugepages or "50% of 512GB" for hugepages, they're both the same thing and the number of hugepages will be the same. 

However, if you really want to add the possibility to configure HP by actual memory size, I'd create a variable that defines whether HP should be calculated as a percentage or as a fixed size.

configure_hugepages: true/false
configure_hugepages_by: memory/percentage (with percentage as the default, as it is today)
percent_hugepages:
size_in_gb_hugepages:

And then in the calculation use a jinja if/else to use the correct variable.

**Comment by Rendanic** [comment]
1st part is the configuration of HugePages. Most of our DBAs are known with the calculation and feel a little bit irritated to use the calculation based on a percentage of the physical memory.
I could implement that, because I like to have it. :-)

The 2nd part - the more important one - is using the HugePages in DBCA. As long as you use 'memory_target <> 0' Oracle is unable to use HugePages on Linux. You must use memory_target=0 and pga_aggregate_target and sga_target for the memory sizing of the instance.

**Comment by oravirt** [comment]
1. yeah, ok. Just different approaches ;-) 
I'm definitely not against having an alternate way of setting hugepages (I just want to make sure they're used ;-) ), so go ahead.

2. That is a dbca issue, it doesn't honor using anything else than memory_*  when using a reponsefile. It doesn't matter that you explicitly set it to NOT use memory_* (like I do in the dbca templates) , it just does it anyway. 
I even had a SR opened, but it didn't really go anywhere.
I've been thinking about not using the responsefiles (just using the bare dbca command with all its switches as it seems to accept more init-parameters than using a responsefile) but I haven't been irritated enough yet ;-) Instead I've got a few modules (oracle_parameter/oracle_user/oracle_tablespace etc) that I use as part of the installation and set the parameters I need and create the users/tablespaces etc with that. So in the end, it's been easier to just use the responsefile for the initial creation and then use the modules for post-creation tasks. 

The modules are in the ansible-oracle-modules repo. I usually just clone that into a 'library' folder inside the ansible-oracle repo and call the modules like you call any other module.

**Comment by Rendanic** [comment]
I am linking this issue to #7, because I did already a lot of stuff for creating the database from sql scripts. This is requirred, when a limitted number of options are needed in the data dictionary with multitenant option - hopefully Oracle change this in 12.2. 
There is no other way then using sql scripts atm. So we could go this way for all installations and have a solution for this problem with hugepages.

The idea with the post sql with addional modules is really cool and working.

**Comment by oravirt** [comment]
I had some time over, so as of 44a3cf3f9860f1d6c895e4e8c0edb0557021c55c it is now possible to set the huge page config as an amount of RAM in GB, not just by a percentage.
