### ISSUE TITLE
how to create a listener?

### ISSUE THREAD

**Issue by dataegg** [oravirt/ansible-oracle#135]
I want to create a listener without a database. I managed to install an oracle home and now I want to create a listener like this:

 oracle_listeners_config:
    LISTENER:
    home: 12cR2-home1
    address:
    - host: "{{ansible_hostname}}"
      protocol: TCP
      port: 1521

  listener_installed:
    - home: 12cR2-home1
      listener_name: LISTENER
      state: present

but i faills with:

TASK [oradb-manage-db : listener | create custom configuration in listener.ora] *************************************************************************************************************************************************************
fatal: [lnxXXX]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'item' is undefined\n\nThe error appears to have been in '/home/user/ansible/ansible-oracle/roles/oradb-manage-db/tasks/listener_details.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: listener | create custom configuration in listener.ora\n  ^ here\n"}

**Comment by Rendanic** [comment]
I didn't try it without a database, but it will work with a database, when you limit the execution to listener tasks. Just add the following tag:
`--tags=listener2`

**Comment by dataegg** [comment]
> 
> 
> I didn't try it without a database, but it will work with a database, when you limit the execution to listener tasks. Just add the following tag:
> `--tags=listener2`
Thanks for your reply, I'm sorry but I don't understand. I'm quite new to ansible. Where should I put --tags=listener2?

**Comment by dataegg** [comment]
Thanks for helping me. I added the --tag-listener2 to the command line. But I still het an error. Am I missing something in my listener configuration?

`ansible-playbook playbook.yml -e hostgroup=myhost_group -i /home/user/ansible/hosts --tags=listener2

PLAY [Database Server Installation] *********************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
ok: [dbserver]

TASK [oradb-manage-db : include_tasks] ******************************************************************************************************************************************************************************************************
included: /home/user/ansible/ansible-oracle/roles/oradb-manage-db/tasks/listener_details.yml for dbserver

TASK [oradb-manage-db : debug] **************************************************************************************************************************************************************************************************************
ok: [dbserver] => {
    "msg": "ORACLE_HOME /u01/oracle/db12cR2/home1"
}

TASK [oradb-manage-db : listener | create custom configuration in listener.ora] *************************************************************************************************************************************************************
fatal: [dbserver]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'item' is undefined\n\nThe error appears to have been in '/home/user/ansible/ansible-oracle/roles/oradb-manage-db/tasks/listener_details.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: listener | create custom configuration in listener.ora\n  ^ here\n"}
        to retry, use: --limit @/home/user/ansible/ansible-oracle/db_software_only.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
dbserver                    : ok=3    changed=0    unreachable=0    failed=1
`

**Comment by Rendanic** [comment]
Could you post your db_homes_config and db_homes_installed as well?
I think there is something wrong with the configuration.

**Comment by dataegg** [comment]
> 
> 
> Could you post your db_homes_config and db_homes_installed as well?
> I think there is something wrong with the configuration.

This is my db_homes_config and db_homes_installed

  db_homes_config:
    12cR2-home1:
      home: home1
      oracle_home: /export/oracle/db12cR2/home1
      version: 12.2.0.1
      edition: SE2

  db_homes_installed:
    - home: 12cR2-home1
      apply_patches: False
      state: present
      version: 12.2.0.1

 oracle_listeners_config:
    LISTENER:
    home: 12cR2-home1
    address:
      - host: "{{ansible_hostname}}"
        protocol: TCP
        port: 1521

  listener_installed:
    - home: 12cR2-home1
      listener_name: LISTENER
      state: present
