### ISSUE TITLE
autostart script does not work for oracle 11g

### ISSUE THREAD

**Issue by chrisbrookes** [oravirt/ansible-oracle#140]
- OS: CentOS 7.5.1804, Systemd.

The [manage_oracle_rdbms_procs.sh](https://github.com/oravirt/ansible-oracle/blob/master/roles/oraswdb-install/files/manage_oracle_rdbms_procs.sh) script that is used to manage the auto start/stop of dbs does not seem to detect that my oracle 11g DB is up, even though it is, and so won't shut it down.

The script uses `ps -C ora_pmon_${ORACLE_SID}` to check if the DB is up. I have a vm with both Oracle 18 and 11. This works fine for the 18 instance. If I run the following, it shows the ps command not picking it up for 11 even though the process is there:

```
[oracle@centosora1:orcl11 oracle]$ ps -ef | grep pmon
oracle    2842     1  0 12:24 ?        00:00:00 ora_pmon_orcl11
oracle    4619     1  0 12:33 ?        00:00:00 ora_pmon_orcl18
oracle    5255  2318  0 12:35 pts/0    00:00:00 grep --color=auto pmon
[oracle@centosora1:orcl11 oracle]$ ps -C ora_pmon_orcl18
  PID TTY          TIME CMD
 4619 ?        00:00:00 ora_pmon_orcl18
[oracle@centosora1:orcl11 oracle]$ ps -C ora_pmon_orcl11
  PID TTY          TIME CMD
```
As you can see, it picks up the orcl18 instance fine. Tried a complete reinstall (using Virtualbox vm + vagrant) and it's the same each time. Not sure if this is a linux thing or a oracle thing.

**Comment by chrisbrookes** [comment]
Changing the line:
```bash
ps -C ora_pmon_${ORACLE_SID} > /dev/null 2>&1
```
to this:
```bash
ps -ef | grep [o]ra_pmon_${ORACLE_SID} > /dev/null 2>&1
```
makes it behave as expected for me.

**Comment by Rendanic** [comment]
I can't check all combinations at the moment, but it seems that Oracle changed the presentation of the process names. I have to change the strategy and think about the following solution:
`ps ax | grep "[0-9] ora_pmon_${ORACLE_SID}$"`

That worked for me under RHEL5,6 and 7 for Oracle 10.2, 11.2 and 12.2. (All combinations that were reachable for me at the moment.)
The `ps -C` didn't worked with the tested combinations. That's why I have to replace the `ps -C`

**Comment by Rendanic** [comment]
Could you test the following?

```
-    ps -C ora_pmon_${ORACLE_SID} > /dev/null 2>&1
+    ps ax | grep "[0-9] ora_pmon_${ORACLE_SID}$" > /dev/null 2>&1
```
I tested it with 12.2, but I don't have a deployed environment with 11.2 at the moment.

I prepare a PR for this and wait for your feedback.

**Comment by chrisbrookes** [comment]
Just tested and yes it works for both my 11.2 and 18 instances.

**Comment by chrisbrookes** [comment]
Confirmed fix. Thx.
