### ISSUE TITLE
source does not exist

### ISSUE THREAD

**Issue by pchapman869** [oravirt/ansible-oracle#145]
Hi,
I've tried a number of things and am stumped. Any help would be Greatly appreciated!

ansible version : 2.7, vagrant 2.2  on ubuntu 16.04

Am getting through many tasks ok, but this...

TASK [oraswgi-install : install-home-gi | Extract files to stage-area (GI) (from remote location )] ***
failed: [racnode-dc1-1] (item={u'creates': u'grid/stage/sizes/oracle.crs.12.1.0.2.0.sizes.properties', u'version': u'12.1.0.2', u'filename': u'linuxamd64_12102_grid_1of2.zip'}) => {"changed": false, "item": {"creates": "grid/stage/sizes/oracle.crs.12.1.0.2.0.sizes.properties", "filename": "linuxamd64_12102_grid_1of2.zip", "version": "12.1.0.2"}, "msg": "Source '/media/swrepo/linuxamd64_12102_grid_1of2.zip' does not exist"}

hosts.yml src seems to be ignored!!  I've even put the correct files in /media/swrepo  and made sure it world readable.  The files do exist in /media/swrepo .

even tried this 
. . .
synced_folders:
     - {src: /home/pc/swrepo, dest: /home/pc}

(I cannot seem to enable verbose logging)

**Comment by oravirt** [comment]
Hi - can you show me your host.yml ?

**Comment by pchapman869** [comment]
Thanks Mikael!
.git/vagrant-vbox-rac/hosts.yml 

- basename_vm: racnode-dc1-
  num_vm: 2
  hostgroup: vbox-rac-dc1
  domain: internal.lab
  box: oravirt/ol75
  vagrant_user: vagrant
  vagrant_pass: vagrant
  #vagrant_private_key: /vagrant/base-provision/insecure_private_key
  ram: 6196
  cpu: 1
  base_pub_ip: 192.168.7.10
  base_pub_ip_vip: 192.168.7.110
  scan_addresses: 192.168.7.210,192.168.7.211
  base_priv_ip: 172.16.7.10
  synced_folders:
     - {src: /home/pc/swrepo, dest: /home/pc}
  base_disk_path:
  create_local_disk: true
  local_disks:
     - {name: u01, size: 75, count: 1}
  create_shared_disk: true
  shared_disks:
     - {name: crs, size: 40, count: 1}
     - {name: data, size: 8, count: 1}
     - {name: fra, size: 12, count: 2}
  provisioning: extra-provision/ansible-oracle/vbox-rac-dc1.yml
  provisioning_env_override: true

**Comment by oravirt** [comment]
Ok - one problem is this:
```
synced_folders:
  - {src: /home/pc/swrepo, dest: /home/pc}
```

It has to be changed to:
```
synced_folders:
  - {src: /home/pc/swrepo, dest: /media/swrepo}
```
`src`: is the path on the host
`dest`: is where `src` should be mounted inside the guest (VM)

So in your case, you're mounting` /home/pc/swrepo` at `/home/pc` in the VM's

Try this first and let me know how that goes.

/M

**Comment by pchapman869** [comment]
Thanks Mikael that works fine.

**Comment by pchapman869** [comment]
these scripts save a LOT of time!

**Comment by oravirt** [comment]
That’s the idea ;-)
