### ISSUE TITLE
oradb-manage-db : manage-db | create/manage database error

### ISSUE THREAD

**Issue by matthiaslink77** [oravirt/ansible-oracle#147]
Hi,

I am stuck here with the default installation for 18c on OEL 7.6. 
My ansible version is 2.7.5, python version = 3.7.2 (default, Jan  3 2019, 09:14:01) [GCC 8.2.1 20181215 (Red Hat 8.2.1-6)]

The VM i am trying to install on is Oracle Linux 7.6 with UEK5.

This command was issued:
ansible-playbook single-instance-db-on-fs.yml -e hostgroup=ora-db-servers -i ../inventory  -vvv

Everything before works ok, but then here it breaks:

...

TASK [oradb-manage-db : manage-db | create/manage database] ******************************************************************
task path: /home/<user>/ansible-oracle/roles/oradb-manage-db/tasks/manage-db.yml:93
...
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 140, in run
    res = self._execute()
  File "/usr/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 612, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python3.7/site-packages/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/lib/python3.7/site-packages/ansible/plugins/action/__init__.py", line 738, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/usr/lib/python3.7/site-packages/ansible/plugins/action/__init__.py", line 177, in _configure_module
    environment=final_environment)
  File "/usr/lib/python3.7/site-packages/ansible/executor/module_common.py", line 973, in modify_module
    environment=environment)
  File "/usr/lib/python3.7/site-packages/ansible/executor/module_common.py", line 791, in _find_module_utils
    recursive_finder(module_name, b_module_data, py_module_names, py_module_cache, zf)
  File "/usr/lib/python3.7/site-packages/ansible/executor/module_common.py", line 538, in recursive_finder
    tree = ast.parse(data)
  File "/usr/lib64/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 328
    if line.startswith('#') or line.startswith(' '):
                                                   ^
TabError: inconsistent use of tabs and spaces in indentation

fatal: [...]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

The relevant file should be: roles/oradb-manage-db/tasks/manage-db.yml

and the relevant line(s):

- name: manage-db | create/manage database
  oracle_db:
        oracle_home={{ oracle_home_db}}
        port={{ listener_port_template }}
        sys_password={{ dbca_sys_pass }}
        db_name={{ dbh.oracle_db_name }}
        db_unique_name={{ dbh.oracle_db_unique_name |default(omit) }}
        sid={{ dbh.oracle_db_instance_name |default(omit) }}
        responsefile={{ oracle_rsp_stage }}/{{ oracle_dbca_rsp }}
        archivelog={{ dbh.archivelog | default (omit)}}
        flashback={{ dbh.flashback | default (omit)}}
        force_logging={{ dbh.force_logging | default (omit)}}
        initparams={{ init_params_list | default(omit)}}
        output=verbose
        state={{ dbh.state}}
  run_once: "{{ configure_cluster }}"
  become_user: "{{ oracle_user }}"
  when: dbh.state|lower == 'present'
  register: dbca_create
  tags: create_db,manage_db,dbca

I already checked the file and could not find any reason, why the format should not be ok. No tabs etc. Do you have any idea what could be the issue?

Best regards, Matthias.

**Comment by oravirt** [comment]
I'll have a look at this.

**Comment by matthiaslink77** [comment]
Thanks. I investigated a bit further: Seems like it is either related to the ansible or the python-version.

With Oracle Linux 7.6 on the ansible control machine and the following versions the installations works without issues:

ansible 2.7.0, python version = 2.7.5 (default, Nov  1 2018, 03:12:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36.0.1)]

I will try to downgrade python on fedora 29 / mac os x to see if it works then as well.

**Comment by oravirt** [comment]
I haven't looked at this properly yet, but the python version is my suspicion as well.

And yes, the modules should absolutely work with Python3 as well. I'll dig into this as soon as possible.

**Comment by oravirt** [comment]
Hi,

https://github.com/oravirt/ansible-oracle/commit/6b1c4613ad95dff98c892e8ead1604dc72c40625 should (hopefully) fix this.

**Comment by matthiaslink77** [comment]
Thanks - works for me now with Python 3.7.2. I did not test everything so far, but the basic "single-instance-db-on-fs.yml" went through, which it did not before. So: Thanks a lot! 👍
