### ISSUE TITLE
Add missing oracle_user params to oradb-manage-users

### ISSUE THREAD

**Issue by chrisbrookes** [oravirt/ansible-oracle#148]
Tthe oradb-manage-users role is missing the following parameters from the [ansible-oracle-modules/oracle_user](https://github.com/oravirt/ansible-oracle-modules/blob/master/oracle_user) library:

- default_temp_tablespace
- schema_password_hash
- authentication_type

 Can they be added in when you get a chance?

**Comment by oravirt** [comment]
Yes! I’ll fix that

**Comment by oravirt** [comment]
cdfb14ec21836df486f89b5223059111eb062740 should take care of `default_temp_tablespace` & `authentication_type`.

`schema_password_hash` is not done yet.

**Comment by chrisbrookes** [comment]
Confirmed default_temp_tablespace works. Thx.

**Comment by Rendanic** [comment]
schema_password_hash is done with  https://github.com/oravirt/ansible-oracle/commit/a54814bcbf7656360007dee360f6d5d65a06df1f

**Comment by Rendanic** [comment]
I never used authentication_type in >23 years of working with oracle at a log of customers.
Please open a new Issue, when this is really needed.

Closing this, because the main requests are finished.
