### ISSUE TITLE
change motd fails with FQDN in inventory (roles/common/templates/motd.j2)

### ISSUE THREAD

**Issue by matthiaslink77** [oravirt/ansible-oracle#149]
Hi Mikael,

thanks for this very cool scripts. I am so glad you invested all this time and effort into it. Very much appreciated!

After playing around a little bit more, I came across the following issue:

If I am are running the playbook against a hostgroup which consists out of FQDNs for the hostnames in the inventory,

[ora-db-servers]
server01.domain.local

the playbook fails, as it tries to use the hostname without the domain (ansible_hostname) at changing the motd.

If I change the motd.j2 line to inventory_hostname, all works fine.

{{a}}: {{ hostvars[inventory_hostname]['ansible_'~a]['ipv4']['address'] }}

Is there something I missed?

Best regards,
Matthias.

**Comment by oravirt** [comment]
https://github.com/oravirt/ansible-oracle/commit/2f84456f924b131e70765360a06bdf361ea35ecf should fix this
