### ISSUE TITLE
orasw-meta: How to find out about which patch needs "creates: ..."?

### ISSUE THREAD

**Issue by matthiaslink77** [oravirt/ansible-oracle#150]
Hi Mikael,

the orasw-meta role lists all patches that can be installed. If newer Patches are released, it would be very helpful to know how to determine the parameter values for "creates: ...".

Can you please let us know how to find out? I could not find too much info on it so far.

Thanks and best regards,
Matthias.

**Comment by matthiaslink77** [comment]
example for older patches:

     - { filename: p28183653_122010_Linux-x86-64.zip, patchid: 28183653, version: 12.2.0.1,  patchversion: 12.2.0.1.180717, description: GI-RU-July-2018, **creates: 28183653/28163133/files/suptools/orachk.zip** }
     - { filename: p27468969_122010_Linux-x86-64.zip, patchid: 27468969, version: 12.2.0.1,  patchversion: 12.2.0.1.180417, description: GI-RU-April-2018, creates: 27468969/27674384/README.txt }
     - { filename: p28140658_12201180417DBAPR2018RU_Linux-x86-64.zip, patchid: 28140658, version: 12.2.0.1,  patchversion: 12201180417DBAPR2018RU , description: 'PARALLEL QUERY Patch for Bug# 28140658 for Linux-x86-64 Platforms', creates: online/files/hpatch/bug28140658.pch }

**Comment by oravirt** [comment]
Hi,

I just manually unzip the file(s) and whatever the last extracted file is, that is what I use as the `creates` key in the list for that zip file. 
It is just a convenience thing to speed up/skip the extract process if the zip-file is already extracted.

e.g
```
[user@host oracle ]$ unzip p6880880_122010_Linux-x86-64.zip
Archive:  p6880880_122010_Linux-x86-64.zip
   creating: OPatch/
  inflating: OPatch/operr
  inflating: OPatch/datapatch
....
   creating: OPatch/docs/
  inflating: OPatch/docs/cversion.txt
  inflating: OPatch/docs/FAQ
  inflating: OPatch/docs/Users_Guide.txt
  inflating: OPatch/docs/Prereq_Users_Guide.txt <-- This is the file I would use as the 'creates' key
[user@host oracle ]
```

Hope that makes it more clear
regards
/M

**Comment by matthiaslink77** [comment]
Perfect. Thanks. Now it's clear :-) 👍
