### ISSUE TITLE
transfer-files.yml checks for attribute apply, but example db-homes.yml uses state for patching

### ISSUE THREAD

**Issue by matthiaslink77** [oravirt/ansible-oracle#151]
Hi Mikael,

now I struggled with the patching, as the following situation came up:

If you choose in db-homes.yml

apply_patches_db: true

the example uses: state: absent or present

But the actual logical check expects apply (not state) to be true.

roles/oraswdb-manage-patches/tasks/transfer-files.yml

It uses the following condition:

when: apply_patches_db and item[1].patchid == item[0].patchid and item[1].apply and oracle_sw_copy and not is_sw_source_local

So the patching fails with:

'dict object' has no attribute 'apply'

fatal: [hostname]: FAILED! => {
    "msg": "The conditional check 'apply_patches_db and item[1].patchid == item[0].patchid and item[1].apply and oracle_sw_copy and not is_sw_source_local' failed. The error was: error while evaluating conditional (apply_patches_db and item[1].patchid == item[0].patchid and item[1].apply and oracle_sw_copy and not is_sw_source_local): 'dict object' has no attribute 'apply'\n\nThe error appears to have been in '/home/matlink/ansible-oracle/roles/oraswdb-manage-patches/tasks/transfer-files.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: gi-opatch | Copy oracle GI patch (opatchauto) to server (www)\n  ^ here\n"
}

I added apply: true to the db-home config and the script continued. I assume state can be removed then and be replaced. Or the transfer-files.yml can be modified to check on state instead of apply?

  12201-181016:
     home: dbhome_1
     version: 12.2.0.1
     edition: EE
     opatch_minversion: 12.2.0.1.13
     opatchauto:
         - patchid: 28714316
           patchversion: 12.2.0.1.181016
           state: absent
           apply: true
           subpatches:
               - 26839277
               - 28662626
               - 28566910
               - 28662603
               - 28662640
     opatch: []

Maybe you can have a look at this? 

Thanks a lot and best regards,
Matthias.

**Comment by Rendanic** [comment]
There are a lot of changes in 3.0.0 regarding patching.
I do a lot of tests with Patching existing Homes and removing old OneOffs - so a lot of cases are tested.

Please check it again and open a new Issue, if the problem is already there.
