### ISSUE TITLE
"orahost : User | Add group(s)" fails with "groupmod: GID '54324' already exists"

### ISSUE THREAD

**Issue by jvolanen** [oravirt/ansible-oracle#160]
Hi

I'm migrating from Oracle XE 18c to 18c EE. The OS is Centos 7.6.

I assume Oracle XE 18c created some of the groups and now there is a conflict between group ids. Orahost role tries to install group oper
but that id is already taken with different id:
```
$ grep 54323 /etc/group
oper:x:54323:oracle
```

**Comment by oravirt** [comment]
Hi,

I'm not sure which task this errors in so I'll just assume that it's in the `User | Add group(s)` task.
There is not much I can do about this unfortunately as this is just how the `group` module works. What you _could_ do is setup your own group_vars with the existing groups/gids and that would work around the problem.

The default group definition is located in `roles/orahost/default/main.yml`  and the variable of interest is `oracle_groups`

**Comment by jvolanen** [comment]
Hi,

Yes, you assume the task correctly. Sorry about unclear description. The workaround you suggested worked perfectly, thanks. 
Is it mandatory to have specific gid for each group? The gid attribute is optional in Ansible [group module](https://docs.ansible.com/ansible/latest/modules/group_module.html) and by removing it the task would not fail in my case.

**Comment by oravirt** [comment]
Great!

> Is it mandatory to have specific gid for each group?

It is not strictly needed, but when setting up user equivalence for RAC installations the gids needs to match up between nodes and there _is_ a possibility that a gid could be taken on one node and not another.
I also try to follow the same pattern as you get if you use the pre-installation rpm that is available.

**Comment by jvolanen** [comment]
Hi
Is it possible to have one list of groups for non-RAC (without GID) and one for RAC (with GID)? That would make non-RAC installation more robust.
