### ISSUE TITLE
manage_oracle_rdbms_procs.sh support for specifying SID

### ISSUE THREAD

**Issue by chrisbrookes** [oravirt/ansible-oracle#165]
At the moment in [manage_oracle_rdbms_procs.sh](https://github.com/oravirt/ansible-oracle/blob/master/roles/oraswdb-install/files/manage_oracle_rdbms_procs.sh), there is an option -`s|--ORACLE_SID` that is not hooked up to anything. This would presumbly start or stop a single DB rather than all of the SIDs in the /etc/oratab file. I've done some changes for this and will submit a PR.

**Comment by Rendanic** [comment]
The PR looks fine for me. Hopefully Mikael find some time to merge it..
