### ISSUE TITLE
how to install two node RAC using Ansible?

### ISSUE THREAD

**Issue by aliyesami** [oravirt/ansible-oracle#168]
I am using this site "https://github.com/oravirt/ansible-oracle"  as reference but the yml file used there is only referring to one node . 
can someone guide me on exactly which files to use ?  

thanks

**Comment by oravirt** [comment]
Hi, first of all - thanks for trying this out!

You need to be more specific - which file are you referring to?

**Comment by aliyesami** [comment]
for a two node RAC install is this going to be my playbook ? full-rac-install-dc1.yml  
also I want to remove the steps for storage configurations since system admins already did that,, can you please guide me on how to remove it ?
thanks

**Comment by aliyesami** [comment]
I started with a simple file that just setup the ssh between two nodes, its working fine for oracle user but it skips the ssh setup for grid user for some reason, can you tell why ?

---------------------- files ------------------------------------------------------------------------
ansible-playbook -i hosts full-rac-install.yml -u kn857sa -k -K



[kn857sa@dotstoans101 ansible-oracle-master]$ more full-rac-install.yml
---


 - name: ssh configuration
   hosts: orarac
   user: kn857sa
   become: yes
   serial: 1
   roles:
      - {role: orahost-ssh}

--------------------------------------------- ERROR -----------------------------------------------------


TASK [orahost-ssh : ssh-keys | get public key for oracle user] ***************************************************************************************************************************
changed: [dotstodb750]

TASK [orahost-ssh : ssh-keys | get public key for grid user] *****************************************************************************************************************************
skipping: [dotstodb750]

TASK [orahost-ssh : ssh-keys | Add keys for oracle user] *************************************************************************************************************

TASK [orahost-ssh : ssh-keys | Add keys for grid user] ***********************************************************************************************************************************
skipping: [dotstodb750]

TASK [orahost-ssh : ssh-keys | create .known_hosts] **************************************************************************************************************************************
ok: [dotstodb750] => (item=oracle)

**Comment by aliyesami** [comment]
even from the start when he is getting the public keys , it skips the "grid" user 

TASK [orahost-ssh : ssh-keys | get public key for oracle user] ***************************************************************************************************************************
changed: [dotstodb749]

TASK [orahost-ssh : ssh-keys | get public key for grid user] *****************************************************************************************************************************
skipping: [dotstodb749]

**Comment by aliyesami** [comment]
ok I fixed this issue , I have another issue though , I will open a new thread since its different issue.
thanks for your help

**Comment by oravirt** [comment]
Ok, great.
Just for reference, if you want to have the `grid` user own the GI this needs to be set:
`role_separation: True`.
That will also set up the keys for the grid user

**Comment by aliyesami** [comment]
Thanks
Can you please see the other issue I opened ?
I am really excited to work with your solution
Regards

On Apr 23, 2019 13:58, Mikael Sandström <notifications@github.com> wrote:

Ok, great.
Just for reference, if you want to have the grid user own the GI this needs to be set:
role_separation: True.
That will also set up the keys for the grid user
