### ISSUE TITLE
help needed for the oraswgi-install

### ISSUE THREAD

**Issue by aliyesami** [oravirt/ansible-oracle#169]
I have successfully setup ssh using your role orahost-ssh, now i am trying to use the role " - oraswgi-install"

in the directory /ansible-oracle-master/roles/oraswgi-install/ i have one file and three folders 

1)clone.sh  <<< what is this file for ?
2)defaults  <<< do i have to use it and if yes then do i have to replace values for 
                "your.scan.address" , "-vip" , "oracle_is_net"   ?
                and what value should i give to oracle_ic_net? 
        
  oracle_scan: your.scan.address                                   
  oracle_vip: -vip                                                 
  oracle_scan_port: 1521                                           
  oracle_ic_net: 3.3.3.{{ ansible_all_ipv4_addresses[0].split(".")[-1] }} 
  oracle_asm_init_dg: crs

3)tasks               << do i have to modify any of the files here?

4)templates           << do i have to modify any of the files here?

 

3)tasks               << do i have to modify any of the files here?

4)templates           << do i have to modify any of the files here?

**Comment by aliyesami** [comment]
also I have created a folder orarac (based on my host group) and the following files based on your example:
please see below the questions I have for password section
[kn857sa@dotstoans101 orarac]$ pwd
/home/kn857sa/ans/ansible-oracle-master/group_vars/orarac
[kn857sa@dotstoans101 orarac]$
[kn857sa@dotstoans101 orarac]$
[kn857sa@dotstoans101 orarac]$ ls
orarac.yml  passwords.yml
[kn857sa@dotstoans101 orarac]$
[kn857sa@dotstoans101 orarac]$
[kn857sa@dotstoans101 orarac]$ more passwords.yml
# GI
default_gipass: xxxxx     <<<<<<<<<<<<< is this grid os account password? 
sysasmpassword: xxxxx
asmmonitorpassword: xxxxxx

# DB
default_dbpass: xxxxxx  <<<<<<<<<<<< which is this password ?
dbpasswords:
      orclcdb:
        system: xxxxx
        sys: xxxxxx
        dbsnmp: xxxxx
        pdbadmin: xxxxxx

**Comment by aliyesami** [comment]
in the group_vars\orarac what should i put for oracle_vip since we have two vips , one for each node.
oracle_vip:

here is the line from the response file from grid showing two vips
oracle.install.crs.config.clusterNodes=dotstodb749:edw-pd-db-vip1,dotstodb750:edw-pd-db-vip2

**Comment by aliyesami** [comment]
last but not least error ,its asking for a response file , how do I get the response file ? its normally created when you install the grid or database , and in my case I am trying to install it .  

fatal: [dotstodb749]: FAILED! => {"changed": true, "cmd": "/u01/stage/12.1.0.2/grid/runInstaller -responseFile /u01/stage/rsp/grid-orarac.rsp -waitforcompletion -ignorePrereq 

The given response file /u01/stage/rsp/grid-orarac.rsp is not found.

**Comment by oravirt** [comment]
> I have successfully setup ssh using your role orahost-ssh, now i am trying to use the role " - oraswgi-install"
> 
> in the directory /ansible-oracle-master/roles/oraswgi-install/ i have one file and three folders
> 
> 1)clone.sh <<< what is this file for ?
> 2)defaults <<< do i have to use it and if yes then do i have to replace values for
> "your.scan.address" , "-vip" , "oracle_is_net" ?
> and what value should i give to oracle_ic_net?
> 
> oracle_scan: your.scan.address
> oracle_vip: -vip
> oracle_scan_port: 1521
> oracle_ic_net: 3.3.3.{{ ansible_all_ipv4_addresses[0].split(".")[-1] }}
> oracle_asm_init_dg: crs
> 
> 3)tasks << do i have to modify any of the files here?
> 
> 4)templates << do i have to modify any of the files here?
> 
> 3)tasks << do i have to modify any of the files here?
> 
> 4)templates << do i have to modify any of the files here?

You should not have to touch anything under `roles/whatever-role-name`. That is just the code that will enforce/apply whatever you have under your `group_vars/your-config`. 
Everything under `roles/whatever-role-name/defaults/` are just default variables and runtime variables

**Comment by oravirt** [comment]
> also I have created a folder orarac (based on my host group) and the following files based on your example:
> please see below the questions I have for password section
> [kn857sa@dotstoans101 orarac]$ pwd
> /home/kn857sa/ans/ansible-oracle-master/group_vars/orarac
> [kn857sa@dotstoans101 orarac]$
> [kn857sa@dotstoans101 orarac]$
> [kn857sa@dotstoans101 orarac]$ ls
> orarac.yml passwords.yml
> [kn857sa@dotstoans101 orarac]$
> [kn857sa@dotstoans101 orarac]$
> [kn857sa@dotstoans101 orarac]$ more passwords.yml
> 
> # GI
> default_gipass: xxxxx <<<<<<<<<<<<< is this grid os account password?
> sysasmpassword: xxxxx
> asmmonitorpassword: xxxxxx
> 
> # DB
> default_dbpass: xxxxxx <<<<<<<<<<<< which is this password ?
> dbpasswords:
> orclcdb:
> system: xxxxx
> sys: xxxxxx
> dbsnmp: xxxxx
> pdbadmin: xxxxxx

All these passwords are either ASM passwords or database passwords

**Comment by oravirt** [comment]
> in the group_vars\orarac what should i put for oracle_vip since we have two vips , one for each node.
> oracle_vip:
> 
> here is the line from the response file from grid showing two vips
> oracle.install.crs.config.clusterNodes=dotstodb749:edw-pd-db-vip1,dotstodb750:edw-pd-db-vip2

Typically a `vip` dns entry has -vip at the end, 
e.g `hostname` is `racnode1` and the vip would then be `racnode1-vip`
So unless it is called something else you shouldn't have to touch that

**Comment by oravirt** [comment]
> last but not least error ,its asking for a response file , how do I get the response file ? its normally created when you install the grid or database , and in my case I am trying to install it .
> 
> fatal: [dotstodb749]: FAILED! => {"changed": true, "cmd": "/u01/stage/12.1.0.2/grid/runInstaller -responseFile /u01/stage/rsp/grid-orarac.rsp -waitforcompletion -ignorePrereq
> 
> The given response file /u01/stage/rsp/grid-orarac.rsp is not found.

The responsefile is generated based on your input and the used in that step.
It is created in this step: 
`- name: install-home-gi | Setup response file for install (GI)`

**Comment by aliyesami** [comment]
ok so in my case the response file is not being generated … how can I debug why ?

**Comment by aliyesami** [comment]
ok so issue is its not generating the response file even though the yml file has the entry to create it .


TASK [oraswgi-install : install-home-gi | Setup response file for install (GI)] ****************************************************************************
skipping: [dotstodb749] => (item={u'attributes': [{u'name': u'compatible.rdbms', u'value': u'11.2.0.4.0'}, {u'name': u'compatible.asm', u'value': u'12.2.0.1'}], u'disk': [{u'device': u'/dev/sdc1', u'asmlabel': u'OCR1'}], u'diskgroup': u'OCRVOTE', u'properties': [{u'redundancy': u'external', u'ausize': 4}]})
skipping: [dotstodb749] => (item={u'attributes': [{u'name': u'compatible.rdbms', u'value': u'11.2.0.4.0'}, {u'name': u'compatible.asm', u'value': u'12.2.0.1'}], u'disk': [{u'device': u'/dev/sdd1', u'asmlabel': u'FRA'}], u'diskgroup': u'FRA', u'properties': [{u'redundancy': u'external', u'ausize': 4}]})
skipping: [dotstodb749] => (item={u'attributes': [{u'name': u'compatible.rdbms', u'value': u'11.2.0.4.0'}, {u'name': u'compatible.asm', u'value': u'12.2.0.1'}], u'disk': [{u'device': u'/dev/sde1', u'asmlabel': u'DATA1'}], u'diskgroup': u'DATA', u'properties': [{u'redundancy': u'external', u'ausize': 4}]})
skipping: [dotstodb749] => (item={u'attributes': [{u'name': u'compatible.rdbms', u'value': u'11.2.0.4.0'}, {u'name': u'compatible.asm', u'value': u'12.2.0.1'}], u'disk': [{u'device': u'/dev/sdf1', u'asmlabel': u'DATA2'}], u'diskgroup': u'DATA', u'properties': [{u'redundancy': u'external', u'ausize': 4}]})

TASK [oraswgi-install : install-home-gi | Install Grid Infrastructure] *************************************************************************************
fatal: [dotstodb749]: FAILED! => {"changed": true, "cmd": "/u01/app/12.2.0.1/grid/gridSetup.sh -responseFile /u01/stage/rsp/grid-orarac.rsp -waitforcompletion -ignorePrereq -silent", "delta": "0:00:01.049396", "end": "2019-04-25 15:26:00.419864", "msg": "non-zero return code", "rc": 255, "start": "2019-04-25 15:25:59.370468", "stderr": "", "stderr_lines": [], "stdout": "Launching Oracle Grid Infrastructure Setup Wizard...\n\n[FATAL] [INS-10101] The given response file /u01/stage/rsp/grid-orarac.rsp is not found.\n   CAUSE: The given response file is either not accessible or do not exists.\n   ACTION: Give a correct response file location. (Note: relative path is not supported)", "stdout_lines": ["Launching Oracle Grid Infrastructure Setup Wizard...", "", "[FATAL] [INS-10101] The given response file /u01/stage/rsp/grid-orarac.rsp is not found.", "   CAUSE: The given response file is either not accessible or do not exists.", "   ACTION: Give a correct response file location. (Note: relative path is not supported)"]}

**Comment by aliyesami** [comment]
after hard coding the resp filename ,its creating the response file but now its failing with the following error, its not liking the  LOCAL_ASM_STORAGE option 

TASK [oraswgi-install : install-home-gi | Install Grid Infrastructure] *************************************************************************************
fatal: [dotstodb749]: FAILED! => {"changed": true, "cmd": "/u01/app/12.2.0.1/grid/gridSetup.sh -responseFile /u01/stage/rsp/grid-orarac.rsp -waitforcompletion -ignorePrereq -silent", "delta": "0:00:01.184853", "end": "2019-04-25 17:20:32.327632", "msg": "non-zero return code", "rc": 255, "start": "2019-04-25 17:20:31.142779", "stderr": "", "stderr_lines": [], "stdout": "Launching Oracle Grid Infrastructure Setup Wizard...\n\n[FATAL] [INS-10105] The given response file /u01/stage/rsp/grid-orarac.rsp is not valid.\n   CAUSE: Syntactically incorrect response file. Either unexpected variables are specified or expected variables are not specified in the response file.\n   ACTION: Refer the latest product specific response file template\n   SUMMARY:\n       - cvc-enumeration-valid: Value 'standard' is not facet-valid with respect to enumeration '[STANDALONE, DOMAIN, MEMBERDB, MEMBERAPP]'. It must be a value from the enumeration.\ncvc-type.3.1.3: The value 'standard' of element 'oracle.install.crs.config.ClusterConfiguration' is not valid.\ncvc-enumeration-valid: Value 'LOCAL_ASM_STORAGE' is not facet-valid with respect to enumeration '[FILE_SYSTEM_STORAGE, FLEX_ASM_STORAGE, CLIENT_ASM_STORAGE, NEAR_ASM_STORAGE]'. It must be a value from the enumeration.\ncvc-type.3.1.3: The value 'LOCAL_ASM_STORAGE' of element 'oracle.install.crs.config.storageOption' is not valid.", "stdout_lines": ["Launching Oracle Grid Infrastructure Setup Wizard...", "", "[FATAL] [INS-10105] The given response file /u01/stage/rsp/grid-orarac.rsp is not valid.", "   CAUSE: Syntactically incorrect response file. Either unexpected variables are specified or expected variables are not specified in the response file.", "   ACTION: Refer the latest product specific response file template", "   SUMMARY:", "       - cvc-enumeration-valid: Value 'standard' is not facet-valid with respect to enumeration '[STANDALONE, DOMAIN, MEMBERDB, MEMBERAPP]'. It must be a value from the enumeration.", "cvc-type.3.1.3: The value 'standard' of element 'oracle.install.crs.config.ClusterConfiguration' is not valid.", "cvc-enumeration-valid: Value 'LOCAL_ASM_STORAGE' is not facet-valid with respect to enumeration '[FILE_SYSTEM_STORAGE, FLEX_ASM_STORAGE, CLIENT_ASM_STORAGE, NEAR_ASM_STORAGE]'. It must be a value from the enumeration.", "cvc-type.3.1.3: The value 'LOCAL_ASM_STORAGE' of element 'oracle.install.crs.config.storageOption' is not valid."]}

**Comment by Rendanic** [comment]
A refactoring of existing inventory is planned for a later time.

A good example is here:
https://github.com/opitzconsulting/ansible-oracle-inventory
