### ISSUE TITLE
Listener management 

### ISSUE THREAD

**Issue by Badmullafo** [oravirt/ansible-oracle#170]
Hi,

Great work! I have been using some of your content to create and configure some fairly simple single instance file system based databases. I've found the modules to be particularly useful!

This isn't an issue as such, more of a question. I've been looking for something that manages listeners i.e starts, stops, restarts, installs. I think I came across something that stopped/started instances/listeners attributed to an Oracle home, however it didn't seem to have the extended functionality mentioned above. Am I missing something?

Thanks

Alex

**Comment by Rendanic** [comment]
The existing start/stop scripts in systemd will be replaced by a new one.
See: https://github.com/oravirt/ansible-oracle/issues/265
