### ISSUE TITLE
Problem with  OPatch in oraswgi-install

### ISSUE THREAD

**Issue by Rendanic** [oravirt/ansible-oracle#174]
I am working on an issue in _oraswgi-install_ with OPatch.
The include_role _orawgi-opatch_ is missing in _oraswgi-install_ and GI 18c + PSU 2019.04 could not be installed before `gridSetup.sh`.

The update of OPatch is missing in oraswgi-install which leads to the following error:
> The OPatch being used has version 12.2.0.1.14 while the following patch(es) require higher versions: Patch 29301631 requires OPatch version 12.2.0.1.16.

The installation of OPatch is different in _oraswgi-opatch_ compared to _oraswdb-manage-patches_. It is still working in _oraswdb-manage-patches_ and _oraswgi-opatch_ should behave the same way.

I am working on a solution for this issue.

**Comment by oravirt** [comment]
The role to manage GI patches is ` oraswgi-manage-patches`, not oraswgi-opatch (that should probably be removed)

**Comment by Rendanic** [comment]
I still found the reason why it is not working in _oraswgi-install_.
I'll create a PR after the testing has been completed.

**Comment by Rendanic** [comment]
Fixed with PR #175
