### ISSUE TITLE
Usage of public-yum.repo deprecated since January 2019

### ISSUE THREAD

**Issue by Rendanic** [oravirt/ansible-oracle#177]
The usage of the public-yum repository files has been deprecated in January 2019.
Details from Oracle:
https://docs.oracle.com/cd/E52668_01/F14052/html/notice_description.html

I like to change the default behavior of ansible-oracle for the following task:

```
  - name: Get newest repo-file for OL (public-yum)
    get_url: dest={{ repo_dir}}/{{ ol_repo_file }}  url=http://public-yum.oracle.com/{{ ol_repo_file }} backup=yes
    when: configure_public_yum_repo and ansible_distribution == 'OracleLinux'

```
The variable configure_public_yum_repo should be changed to False.
This will break old OS templates without a public-yum repositoriydefinition. New OS templates without a public-yum repositofyfile will be messed up with this task and leads to duplicate repository definitions.
We could add another task to check against a RPM from the new definitions but I think that this is not needed due to the fact that every installation should be execute a 'yum update -y' with a migration to the new repositorydefinnitions before the start of ansible-oracle.

**Comment by oravirt** [comment]
I will look into this, but I _think_ what could/should be done is to check for the existence of the old monolithic file, and if it exists make sure the correct release package `oraclelinux-release-el7/el6` is installed and run the conversion script for the modular configuration (if needed). That effectively disables the monolithic  repo. (Maybe make it an option with `True/False` )

I'll do some tests.

I should also probably replace the `epel` repo with the `oracle-epel` repo for OL systems.

**Comment by Rendanic** [comment]
#205
