### ISSUE TITLE
Create Listener in GI

### ISSUE THREAD

**Issue by duhlig** [oravirt/ansible-oracle#181]
Is it possible to create the listener in the GI instead of a DB home? In the simplest and most standard way it's:
```

[set environment to GI]
srvctl add listener
srvctl start listener

```
and the result could be checked with ```crsctl stat res ora.LISTENER.lsnr```.

Kind Regards,
Dietmar

**Comment by Rendanic** [comment]
This has to wait until #266 has been implemented.
