### ISSUE TITLE
oradb-manage-db - Module throwing unknown error

### ISSUE THREAD

**Issue by kiruba87** [oravirt/ansible-oracle#188]
I tried to using oradb-manage-db module to create 18c database but I am getting the below error. Not getting any clue by seeing this error, please help on this. 

Playbook content:

[root@18cpocanbu ansible-oracle-master]# cat single-instance-dbcreation_new.yml
---

 - name: Database Server Installation & Database Creation
   hosts: 104.45.3.126
   user: oracle
   become: yes
   roles:
      - oradb-manage-db

[root@18cpocanbu ansible-oracle-master]#

Error: 
TASK [oradb-manage-db : include_tasks] ******************************************************************************************************************************************************************************************************
fatal: [104.45.3.126]: FAILED! => {"reason": "no action detected in task. This often indicates a misspelled module name, or incorrect module path.\n\nThe error appears to be in '/home/oracle/ansible-oracle-master/roles/oradb-manage-db/tasks/manage-db.yml': line 93, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: manage-db | create/manage database\n  ^ here\n"}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
104.45.3.126               : ok=6    changed=1    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0

**Comment by oravirt** [comment]
This (`{"reason": "no action detected in task. This often indicates a misspelled module name, or incorrect module path.\` ) usually indicates that the module you're trying to use is not found.

Can you give me a `ls -l`  of the directory you're running the playbook from? How did you clone the repo? Did you use `git clone --recursive` ?

**Comment by kiruba87** [comment]
[root@18cpocanbu ansible-oracle-master]# ls -ltr
total 96
-rw-r--r--. 1 oracle oinstall  922 May 31 07:35 vbox-si-fs-install.yml
-rw-r--r--. 1 oracle oinstall 1401 May 31 07:35 vbox-si-asm-install.yml
-rw-r--r--. 1 oracle oinstall 1013 May 31 07:35 vbox-rac-full-install.yml
-rw-r--r--. 1 oracle oinstall 1666 May 31 07:35 vbox-rac-dc2.yml
-rw-r--r--. 1 oracle oinstall 1666 May 31 07:35 vbox-rac-dc1.yml
-rw-r--r--. 1 oracle oinstall  295 May 31 07:35 single-instance-db-on-fs.yml
-rw-r--r--. 1 oracle oinstall  782 May 31 07:35 single-instance-db-on-asm.yml
drwxr-xr-x. 1 oracle oinstall 1028 May 31 07:35 roles
-rw-r--r--. 1 oracle oinstall 5634 May 31 07:35 README.md
-rw-r--r--. 1 oracle oinstall  530 May 31 07:35 racattack-full-install.yml
-rwxr-xr-x. 1 oracle oinstall  142 May 31 07:35 manage-db.yml
-rw-r--r--. 1 oracle oinstall 1133 May 31 07:35 LICENSE
drwxr-xr-x. 1 oracle oinstall    0 May 31 07:35 library
drwxr-xr-x. 1 oracle oinstall   10 May 31 07:35 host_vars
drwxr-xr-x. 1 oracle oinstall  214 May 31 07:35 group_vars
-rwxr-xr-x. 1 oracle oinstall  135 May 31 07:35 gi-opatch.yml
-rw-r--r--. 1 oracle oinstall  805 May 31 07:35 full-rac-install-dc1.yml
-rw-r--r--. 1 oracle oinstall  605 May 31 07:35 full-rac-flex-install.yml
-rw-r--r--. 1 oracle oinstall  539 May 31 07:35 drracattack-full-install.yml
-rwxr-xr-x. 1 oracle oinstall  182 May 31 07:35 delete-db.yml
-rwxr-xr-x. 1 oracle oinstall  235 May 31 07:35 db-opatch.yml
drwxr-xr-x. 1 oracle oinstall  132 May 31 07:35 dbhome-conversion
-rw-r--r--. 1 oracle oinstall  286 May 31 07:35 customize-db.yml
-rwxr-xr-x. 1 oracle oinstall 1092 May 31 07:35 clean.sh
-rw-r--r--. 1 oracle oinstall  777 May 31 07:35 CHANGELOG.md
-rw-r--r--. 1 oracle oinstall  803 May 31 07:35 aws-si-asm-install.yml
drwxr-xr-x. 1 oracle oinstall   54 Aug  2 20:30 inventory
-rw-r--r--. 1 oracle oinstall  150 Aug  3 09:08 single-instance-dbcreation.yml
-rw-r--r--. 1 oracle oinstall  154 Aug  6 14:23 single-instance-dbcreation_new.yml
[root@18cpocanbu ansible-oracle-master]#

**Comment by oravirt** [comment]
Also show me `ls -l library`

**Comment by kiruba87** [comment]
[root@18cpocanbu library]# ls -ltr
total 0
[root@18cpocanbu library]#

**Comment by oravirt** [comment]
You should have followed the readme on how to clone the repo ;-)

All the modules are from a different repo, which is why you have to do `git clone --recursive https://github.com/oravirt/ansible-oracle`
So easiest is just to reclone everything and try again.

**Comment by kiruba87** [comment]
Thanks for your help. I gone through that error. I am getting the below error,

TASK [oradb-manage-db : manage-db | create/manage database] ************************************************************************************************************
fatal: [104.45.3.126]: FAILED! => {"changed": false, "msg": "The cx_Oracle module is required. 'pip install cx_Oracle' should do the trick. If cx_Oracle is installed, make sure ORACLE_HOME & LD_LIBRARY_PATH is set"}

PLAY RECAP *************************************************************************************************************************************************************
104.45.3.126               : ok=12   changed=2    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0

**Comment by oravirt** [comment]
Is cx_Oracle installed on the host (104.43.2.126)?

**Comment by kiruba87** [comment]
Hi 
Cx_oracle is not installed in that host.

**Comment by oravirt** [comment]
Well, it needs to be installed on the host where the module is executed

**Comment by kiruba87** [comment]
The error is resolved and able to create a database. 

I am trying to path the database using oraswdb-manage-patches role. Can I patch 18c database using this role. 

Please help me with any readme document for using this role.

**Comment by Rendanic** [comment]
Version 3.0.0 includes a lot of changes in modules and roles for creating databases.
