### ISSUE TITLE
Compatibility ansible <=> ansible-oracle

### ISSUE THREAD

**Issue by Rendanic** [oravirt/ansible-oracle#194]
What is the oldest version of Ansible which is supported by ansible-oracle?
Some tasks are using deprecated functions and we should change them to the current supported structures. That requires a clear definition of a minimum version of Ansible.

I mostly work with 2.6+.

**Comment by oravirt** [comment]
I'm not really sure... It's definitely 2.something but not sure about the exact version.

Do you have a specific task in mind?

**Comment by Rendanic** [comment]
One example but there are more in other roles:


> TASK [orahost : Install packages required by Oracle on OL/RHEL] *******************************************************
> ok: [oradb03]
> [DEPRECATION WARNING]: Invoking "zypper" only once while using a loop via squash_actions is deprecated. Instead of
> using a loop to supply multiple items and specifying `name: "{{ item }}"`, please use `name: '{{ oracle_packages_sles
> }}'` and remove the loop. This feature will be removed in version 2.11. Deprecation warnings can be disabled by
> setting deprecation_warnings=False in ansible.cfg.

I was not able to find an information which version of Ansible is needed for this change, but it should work in 2.5+.  If we change these task we have to make a decision for a minum supported version of Ansible.

Which version should be defined as a new minimum? That version should be chaeck in an affected role which needs a special minimum version to reduce possible issues from users with old versions of Ansible.

We have to do this decision, because Ansible does not support old versions anymore and some task won't work with future versions...

**Comment by Rendanic** [comment]
I did a test with Ansible 2.9 and hit the following issue:
https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.5.html#jinja-tests-used-as-filters

One example:

```
TASK [orahost : Check for correct OS family & min version] ***********************************************************************************************************************
fatal: [dbfs101]: FAILED! => {"msg": "The conditional check 'ansible_distribution_version | version_compare('6.4', '>=')' failed. The error was: template error while templating string: no filter named 'version_compare'. String: {% if ansible_distribution_version | version_compare('6.4', '>=') %} True {% else %} False {% endif %}"}
```

**Comment by Rendanic** [comment]
The PR #198 is really needed, because ansible 2.9 is incompatible against ansible-oracle. 
Oracle has Ansible 2.9 in thier EPEL-Repository for OL. 
A downgrade to 2.8 is mandatory to work with ansible-oracle at the moment...

**Comment by Rendanic** [comment]
I created #230 for some more changes to make ansible-oracle usable from Ansible 2.8+.
It also adds an assert for a munumum version of Ansible 2.8.

We need this change, because some functions have been deprecated a long tme ago and removed in 2.8+.
