### ISSUE TITLE
Unable to install 18c GI software

### ISSUE THREAD

**Issue by preethik1** [oravirt/ansible-oracle#197]
I am learning Ansible and trying to install RAC. 
I have downloaded GRID and Oralce Software from OTN. But i am confused here: 

My ansible server path: /c/Users/manohar/oracledb-ansible/ansible-oracle/vagrant-vbox-rac/vagrant-vbox-rac/extra-provision/ansible-oracle/roles/oraswgi-install/tasks:

www_download_bin: curl                              # curl (shell module) or get_url module
  oracle_sw_source_www: http://www/orasw     # address to all software if using the get_url module when putting software on the host(s)

Could you please some one help on this.
![racdb_error](https://user-images.githubusercontent.com/59973921/73018863-746ba300-3e48-11ea-8687-61906ac7d2f5.jpg)

**Comment by Rendanic** [comment]
The installation media is missing at the pat showed by te error.

This doesn't look like an issue in ansible-oracle.
