### ISSUE TITLE
Create a 19.3.0.0 Database - netca.rsp.19.3.0.0.j2 is missing

### ISSUE THREAD

**Issue by FrankBergerITServices** [oravirt/ansible-oracle#200]
TASK [oradb-manage-db : listener | Create responsefile for listener configuration] **********************************************************************************
fatal: [192.168.1.15]: FAILED! => {"changed": false, "msg": "Could not find or access 'netca.rsp.19.3.0.0.j2'\nSearched in:\n\t/home/frank/ppi2/ansible-oracle/roles/oradb-manage-db/templates/netca.rsp.19.3.0.0.j2\n\t/home/frank/ppi2/ansible-oracle/roles/oradb-manage-db/netca.rsp.19.3.0.0.j2\n\t/home/frank/ppi2/ansible-oracle/roles/oradb-manage-db/tasks/templates/netca.rsp.19.3.0.0.j2\n\t/home/frank/ppi2/ansible-oracle/roles/oradb-manage-db/tasks/netca.rsp.19.3.0.0.j2\n\t/home/frank/ppi2/ansible-oracle/templates/netca.rsp.19.3.0.0.j2\n\t/home/frank/ppi2/ansible-oracle/netca.rsp.19.3.0.0.j2 on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}

**Comment by Rendanic** [comment]
The netca has to many limitations and problems.
This will be replaced with jinja templates for tnsnamessqlnet-files.
