### ISSUE TITLE
unable to install gi software 19.3.0.0

### ISSUE THREAD

**Issue by shankargarlapati** [oravirt/ansible-oracle#202]
I'm trying to install gi 19.3.0.0 software with ASM. while installing it is giving below error. can you help me on this?

TASK [oraswgi-install : install-home-gi | Setup response file for install (GI)] *******************************************************************************************************************************************
task path: /u01/ansible/ansible-oracle/roles/oraswgi-install/tasks/19.3.0.0.yml:61
fatal: []: FAILED! => {
    "msg": "'asm_diskgroups' is undefined"
}

**Comment by Rendanic** [comment]
This is an issue with the inventory.
A refactoring of current inventory is planned for a later time.

Use the following inventory project as an example:
https://github.com/opitzconsulting/ansible-oracle-inventory
