### ISSUE TITLE
oradb-manage-db : unable to install oracle 18.3.0.0

### ISSUE THREAD

**Issue by watanabebousquet** [oravirt/ansible-oracle#206]
TASK [oradb-manage-db : include_tasks] ********************************************************************************************************************************************************************
task path: /var/lib/awx/projects/ansible-oracle-master/roles/oradb-manage-db/tasks/main.yml:52
fatal: [192.168.56.192]: FAILED! => {
    "reason": "couldn't resolve module/action 'oracle_db'. This often indicates a misspelling, missing collection, or incorrect module path.\n\nThe error appears to be in '/var/lib/awx/projects/ansible-oracle-master/roles/oradb-manage-db/tasks/manage-db.yml': line 93, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: manage-db | create/manage database\n  ^ here\n"
}

Can you give me a solution?  Thanks in advance！

**Comment by nikhil-postgres** [comment]
Hi @watanabebousquet , I am facing the same issue. Did you resolve this?
