### ISSUE TITLE
cx_oracle 8.0 not compatible with Python 2.x anymore

### ISSUE THREAD

**Issue by matthiaslink77** [oravirt/ansible-oracle#209]
The cxoracle role does not install per default anymore, as cx_oracle==7.3 is the last version compatible with python 2.x.

cx_oracle 8.+ require Python 3.x . Currently this is not reflected in the role.

**Comment by Rendanic** [comment]
@matthiaslink77 Could you close this issue?

**Comment by matthiaslink77** [comment]
Good morning Thorsten, thanks a lot. 

Yes - to just add the version to the package name was the fix I already provided in the text. 

This issue was actually opened to fix it "properly", hence version 8.+ should be usable. 

So I would rather like to keep this issue open.

Danke und beste Grüße, Matthias.

**Comment by Rendanic** [comment]
We should close this issue.
Reasons:
- Python3 + Ansible has issues on OL7
Some Ansible modules - not the library inside ansible-oracle - have problems during execution of ansible-playbooks. Solution: Use Ansible with Python2 on OL7. This requires the old version of cx_Oracle.
- Python3 + Ansible is working on OL8

I see no way to fix the issue with newer version of cx_Oracle on OL7 with Python3.
