### ISSUE TITLE
Unable to install some packages  on CentOS

### ISSUE THREAD

**Issue by james0444** [oravirt/ansible-oracle#213]
While trying to install single-instance-db-on-fs.yml below error was observed. I am using CentOS which is based on Redhat architecture. Please help

Error details:
=========
fatal: [devops]: FAILED! => {
    "changed": false,
    "failures": [
        "No package None available."
    ],
    "invocation": {
        "module_args": {
            "allow_downgrade": false,
            "autoremove": false,
            "bugfix": false,
            "conf_file": null,
            "disable_excludes": null,
            "disable_gpg_check": false,
            "disable_plugin": [],
            "disablerepo": [],
            "download_dir": null,
            "download_only": false,
            "enable_plugin": [],
            "enablerepo": [],
            "exclude": [],
            "install_repoquery": true,
            "install_weak_deps": true,
            "installroot": "/",
            "list": null,
            "lock_timeout": 30,
            "name": [
                "None"
            ],
            "releasever": null,
            "security": false,
            "skip_broken": false,
            "state": "installed",
            "update_cache": false,
            "update_only": false,
            "validate_certs": true
        }
    },
    "msg": "Failed to install some of the specified packages",
    "rc": 1,
    "results": []
}

**Comment by Rendanic** [comment]
CentOS is not certified by Oracle.
Please use OracleLinux as a free availible distribution.

**Comment by james0444** [comment]
I tried installing it on Redhat 8 but still this error is observed.

**Comment by Rendanic** [comment]
OL8 and RHEL8 has never been tested and I think it won't work, because the OS-Roles are executing tasks depending on the OS-Version from ansible facts.

**Comment by james0444** [comment]
Yes, it does not work on RHEL 8 so installed RHEL 7.8 and tried installing the single-instance-db-on-fs.yml but it errored out at the orahost task

Error:
===========

TASK [orahost : Check for correct OS family & min version] ******************************************************************************************************************************************************************************
task path: /home/oracle/ansible-oracle/roles/orahost/tasks/main.yml:4
fatal: [192.168.0.117]: FAILED! => {
    "msg": "The conditional check 'ansible_distribution_version | version_compare('6.4', '>=')' failed. The error was: template error while templating string: no filter named 'version_compare'. String: {% if ansible_distribution_version | version_compare('6.4', '>=') %} True {% else %} False {% endif %}"
}

**Comment by james0444** [comment]
Resolved the above error by downgrading the ansible version to 2.8 but now I am stuck at the below mentioned error.
I have already added the  entry of hosts in the /etc/hosts file but still it is erroring out.

Error:
=====

fatal: [192.168.0.117]: FAILED! => {
    "changed": false,
    "cmd": [
        "host",
        "uat"
    ],
    "delta": "0:00:00.145526",
    "end": "2020-08-10 01:45:32.118918",
    "invocation": {
        "module_args": {
            "_raw_params": "host uat",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2020-08-10 01:45:31.973392",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "Host uat not found: 3(NXDOMAIN)",
    "stdout_lines": [
        "Host uat not found: 3(NXDOMAIN)"
    ]
}
...ignoring

TASK [orahost : Add host to /etc/hosts if needed] ***************************************************************************************************************************************************************************************
task path: /home/oracle/ansible-oracle/roles/orahost/tasks/main.yml:75
fatal: [192.168.0.117]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: list object has no element 1\n\nThe error appears to be in '/home/oracle/ansible-oracle/roles/orahost/tasks/main.yml': line 75, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Add host to /etc/hosts if needed\n    ^ here\n"
}

**Comment by james0444** [comment]
Solved this error too by manually editing the /etc/hostname

**Comment by Rendanic** [comment]
Version 3.0.0 should fix this problem.
I test that release against OL7 and OL8
