### ISSUE TITLE
[INS-30508] Invalid ASM disks.

### ISSUE THREAD

**Issue by james0444** [oravirt/ansible-oracle#214]
I am trying to install Single instance standalone database with Grid but unable to move ahead due to the below error. Please help.

TASK [oraswgi-install : install-home-gi | Install Grid Infrastructure] *************************************************************************************************
task path: /home/oraefx/ansible-oracle/roles/oraswgi-install/tasks/12.1.0.2.yml:43
fatal: [199.1.0.200]: FAILED! => {
    "changed": true,
    "cmd": "/u01/stage/12.1.0.2/grid/runInstaller -responseFile /u01/stage/rsp/grid-myhostgroup.rsp -waitforcompletion -ignorePrereq -ignoreSysPrereqs -showProgress -silent",
    "delta": "0:00:04.616256",
    "end": "2020-08-14 09:02:31.186901",
    "invocation": {
        "module_args": {
            "_raw_params": "/u01/stage/12.1.0.2/grid/runInstaller -responseFile /u01/stage/rsp/grid-myhostgroup.rsp -waitforcompletion -ignorePrereq -ignoreSysPrereqs -showProgress -silent",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 254,
    "start": "2020-08-14 09:02:26.570645",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "Starting Oracle Universal Installer...\n\nChecking Temp space: must be greater than 415 MB.   Actual 138449 MB    Passed\nChecking swap space: must be greater than 150 MB.   Actual 20478 MB    Passed\nPreparing to launch Oracle Universal Installer from /tmp/OraInstall2020-08-14_09-02-26AM. Please wait ...[FATAL] [INS-30508] Invalid ASM disks.\n   CAUSE: The disks [ORCL:CRS01] were not valid.\n   ACTION: Please choose or enter valid ASM disks.\nA log of this session is currently saved as: /tmp/OraInstall2020-08-14_09-02-26AM/installActions2020-08-14_09-02-26AM.log. Oracle recommends that if you want to keep this log, you should move it from the temporary location.",
    "stdout_lines": [
        "Starting Oracle Universal Installer...",
        "",
        "Checking Temp space: must be greater than 415 MB.   Actual 138449 MB    Passed",
        "Checking swap space: must be greater than 150 MB.   Actual 20478 MB    Passed",
        "Preparing to launch Oracle Universal Installer from /tmp/OraInstall2020-08-14_09-02-26AM. Please wait ...[FATAL] [INS-30508] Invalid ASM disks.",
        "   CAUSE: The disks [ORCL:CRS01] were not valid.",
        "   ACTION: Please choose or enter valid ASM disks.",
        "A log of this session is currently saved as: /tmp/OraInstall2020-08-14_09-02-26AM/installActions2020-08-14_09-02-26AM.log. Oracle recommends that if you want to keep this log, you should move it from the temporary location."
    ]
}

**Comment by Rendanic** [comment]
Hi,
check your inventory in ansible:
`ansible-inventory -i <hostfile for inventory> --host <hostname>`
Example from my environment:
`ansible-inventory -i inventory/restart/hosts.yml --host oradb04`

You can add a '-y' for yaml output instead of json.

I always check it this way, because this is the real inventory during the execution of the playbook.

**Comment by Rendanic** [comment]
Looks like an error in inventory.
