### ISSUE TITLE
RHEL version check assertion fails in ansible version 2.9.6

### ISSUE THREAD

**Issue by Ranzo3** [oravirt/ansible-oracle#215]
TASK [orahost : Check for correct OS family & min version] *********************************************************************************************************************************************
fatal: [44.234.188.63]: FAILED! => {"msg": "The conditional check 'ansible_distribution_version | version_compare('6.4', '>=')' failed. The error was: template error while templating string: no filter named 'version_compare'. String: {% if ansible_distribution_version | version_compare('6.4', '>=') %} True {% else %} False {% endif %}"}

Internet search seems to indicate this was deprecated in 2.9 of Ansible.
A few changes like the following are needed:

        #- "ansible_distribution_version | version_compare('{{ os_min_supported_version }}', '>=')"
        - "ansible_distribution_version is version('{{ os_min_supported_version }}', '>=')"

**Comment by Rendanic** [comment]
Is also part of PR #230

**Comment by Rendanic** [comment]
PR #230  has been merged.

=> This issue is fixed and could be closed.
