### ISSUE TITLE
/etc/sudoers.d/oracle wrong mode, should be 0440

### ISSUE THREAD

**Issue by Ranzo3** [oravirt/ansible-oracle#216]
After successfully using the project to create Oracle Homes, I later received this when running visudo -c

Checking existing sudoers file syntax...
/etc/sudoers: parsed OK
/etc/sudoers.d/90-cloud-init-users: parsed OK
/etc/sudoers.d/oracle: bad permissions, should be mode 0440
Initial "visudo -c" failed; aborting...

**Comment by Rendanic** [comment]
fixed with #263
