### ISSUE TITLE
Error while trying to run single-instance-on-asm-install.yml

### ISSUE THREAD

**Issue by jamespackiam** [oravirt/ansible-oracle#218]
I am receiving below error while trying to configure ASM, through single-instance-on-asm-install.yml book can someone please help.

TASK [orahost-storage : ASM-storage | partition devices] ***************************************************************************************************************
task path: /export/home/ansible-oracle/roles/orahost-storage/tasks/main.yml:3
fatal: [testx]: FAILED! => {
    "msg": "subelements lookup expects a dictionary, got 'crs'"
}

**Comment by Rendanic** [comment]
Will be replaced by a new inventory and playbook after 3.0.0 release.
