### ISSUE TITLE
chopt gets executed with running oracle instances

### ISSUE THREAD

**Issue by bartowl** [oravirt/ansible-oracle#219]
Hi,

chopt in oraswdb-install/tasks/install-home-db.yml:49 first of all is not idempotent (at least with 19c - logfile created has always a timestamp as part of its name, thus it is changed every time the playbook runs).
What is worse - when some of the options change, and the playbook is started again, it does not check for running instances, and in effect causes changing of options and relinking of oracle binaries with running instances, that start to behave completetly random from that moment on. For example I could not change an spfile parameter with a really weird error message:

15:23:15 SYS @ CDB1:CDB$ROOT:>alter system set processes=1000 scope=spfile;
alter system set processes=1000 scope=spfile
*
ERROR at line 1:
ORA-00068: invalid value 1000 for parameter processes, must be between
268435460 and 18446744073709551615

It should check for running instances and either force shutdown them before, and restart after changing options, or fail if no restart is allowed per additional variable.

**Comment by Rendanic** [comment]
Hi,
this is a known issue and I have a solution for it, but it needs some free time on my side...
This should be an issue in 19c, because Oracle changed the behavior of chopt and that breaks the current implementation.

**Comment by Rendanic** [comment]
I added more stuff to chopt.

- added lsof to default RPMs in orahost
- check against installed lsof in $PATH
- check for running processes in ORACLE_HOME and abort chopt
- force chopt with '-e forcechopt=yes'

I think all important points are solved.

**Comment by jamespackiam** [comment]
Hi Rendanic,

While trying to create the Oracle Database 12.1.0.2 , I am also receiving the same error. Please let me know where are the changes needs to be made so that I can overcome this issue.

Error Details:
============
TASK [oraswdb-install : install-home-db | Change Database options with chopt] ******************************************************************************************
task path: /export/home/ansible-oracle/roles/oraswdb-install/tasks/install-home-db.yml:49
fatal: [localhost]: FAILED! => {
    "msg": "The conditional check 'db_homes_config[dbh.home]['edition'] == 'EE' and oracle_EE_options is defined and disable_EE_options' failed. The error was: error while evaluating conditional (db_homes_config[dbh.home]['edition'] == 'EE' and oracle_EE_options is defined and disable_EE_options): 'dict object' has no attribute 'edition'\n\nThe error appears to be in '/export/home/ansible-oracle/roles/oraswdb-install/tasks/install-home-db.yml': line 49, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# we cannot use default/main.yml here. => complicated structure for 'enabled' 'disabled'...\n- name: install-home-db | Change Database options with chopt\n  ^ here\n"
}

**Comment by Rendanic** [comment]
Hi,
could you check db_homes_config?
The error in you play is:

>  'dict object' has no attribute 'edition'

I think 'edition' is missing in your db_homes_config:

```
db_homes_config:
  db193-latest:
    home: db193-latest
    version: 19.3.0.0
    edition: EE
```

**Comment by jamespackiam** [comment]
Yep, I got the error thanks.
