### ISSUE TITLE
Updating passwords does not "support" characters like '-' or '.'

### ISSUE THREAD

**Issue by fcs69** [oravirt/ansible-oracle#221]
I'm new to github, so I don't know exactly how to raise this issue. Therefore I describe it here!

I had a problem rerunning a playbook when a user already exists:

FAILED ! => {"changed": false, "msg": "Blergh, something went wrong while executing sql - ORA-00922: missing or invalid option sql: alter user itsme identified by ********  default tablespace users quota unlimited on users account unlock"}

**Reason**: Passwort contains characters like '-' and '.'

Solved it by changing the code from

`sql = 'create user %s identified by %s '% (schema, schema_password)`

to

`sql = 'create user %s identified by \"%s\" '% (schema, schema_password)`

**Comment by fcs69** [comment]
Forgot to note the file: 

> oracle_user

**Comment by Rendanic** [comment]
There are some fixes and additions with 3.0.0 regarding password management.
Should be fixed with 3.0.0
