### ISSUE TITLE
How can i install 19.3 (instead of default 18.3)? by edit any file or pass any param?

### ISSUE THREAD

**Issue by exastat** [oravirt/ansible-oracle#227]
Dear,
    How can i install 19.3 (instead of default 18.3)? by edit any file or pass any param?

Thanks & Regards,
Martin.

**Comment by Rendanic** [comment]
An example inventory for ansible-oracle is here:
https://github.com/opitzconsulting/ansible-oracle-inventory

This will be added to ansible-oracle at a later time.
