### ISSUE TITLE
Github Actions with ansible-lint for ansible-oracle

### ISSUE THREAD

**Issue by Rendanic** [oravirt/ansible-oracle#245]
Hi Mikaeel,
I am working on a huge PR (https://github.com/opitzconsulting/ansible-oracle/pull/64) at the moment.
The PR implements Github Actions with ansible-lint for syntax and formatting checks for ansible-oracle.

This currently works for nearly all roles. See `.ansiblelint` for exceptions.

I did a lot of formatting on all roles to make it usable with ansible-lint. The PR is on top of our current oc-Branch. I'll create some PRs, to bring the master on same level as the oc on our site.

It is a huge step for the project and it needs a lot of refactoring on many roles in the future.

Regards
Thorsten

**Comment by oravirt** [comment]
Awesome! 
Thank you so much for all your efforts, I really appreciate it!

**Comment by Rendanic** [comment]
I worked on merging all changes from oc-branch to master with lot of PRs as preparation for the final ansible-lint PR.

The following commits needs some work at later time in ansible-oracle-modules:

- e86e95e oracle_profile: Bugfix for Python3
- 612a9ee oracle_parameter: Support for Python3
- 860d9ee oracle_db: fixed wrong identation
- 7ec00e7 fixed db_domain handling
- 47fc3e9 oracle_db: Bugfix for empty slsql
- dc3a32b oracle_db: fixed ORA-00904: invalid identifier sql: select SUPPLEMENTAL_LOG_DATA_MIN
- 429aaae oracle_db: Bugfix for start_db in Oracle Restart

Don't forget to merge the following PRs as well:
- #225 
- #239 
- #250 
- #251 
- #252 
- #253 
- #254

**Comment by Rendanic** [comment]
We did a lot more changes on our site and I am still working on some interesting stuff for the future.
My main problem is the merge from oc to master.

We should discuss the future of our branch and master on oravirt. The current stae is, that both repositories are for away from sync...

**Comment by Rendanic** [comment]
Planned for 3.0.0

**Comment by Rendanic** [comment]
merged with #260
