### ISSUE TITLE
Stop_processes is not working during patch rollback using opatch

### ISSUE THREAD

**Issue by shivasl2022** [oravirt/ansible-oracle#257]
Hi @oravirt, 
I'm using "oraswdb-manage-patches" role to apply and rollback Oracle Release Update patches.
The issue I noticed is, while applying the patch, the DB services are getting stopped which is good but NOT during the patch rollback. 

I'm setting the variables in ansible-oracle-master/roles/orasw-meta/defaults/main.yml file as shown below.

-     opatch:
         - patchid: 33515361
           patchversion: 19.14.0.0.220118
           state: absent                                <-- If I set 'present', it's stopping the processes and applying the patch. If I set 'absent', it's NOT stopping the processes but rolling back the patch.
           stop_processes: True 

Your help is highly appreciated!

Thank you,
Shiva

**Comment by shivasl2022** [comment]
Hi @oravirt, have you got a chance to take a look at this issue?

Thank you
Shiva

**Comment by Rendanic** [comment]
Did you try the latest version from https://github.com/opitzconsulting/ansible-oracle branch oc?
I remember some bugs in opatch, but can't find the PR for that at the moment.

**Comment by shivasl2022** [comment]
Thanks for your response. Let me try it.

**Comment by Rendanic** [comment]
Should be fixed with #260
