### ISSUE TITLE
Centos 7 support

### ISSUE THREAD

**Issue by Veske** [oravirt/ansible-oracle#27]
Do you have plans to support this OS at any point officially? I got your project working for it but it would need some more modifications to make it more generic for all OS's.

**Comment by oravirt** [comment]
Yes!
It's way overdue, but I'm actually working on that now. I don't have an eta yet, but it shouldn't be long.

**Comment by Veske** [comment]
Nice! Keep up the good work.

**Comment by oravirt** [comment]
As of 0241bdf it is supported to use EL7 environments as well.
Haven't actually tested centos 7 yet but should work.

**Comment by Veske** [comment]
Seems to be similar to what I did. Only thing I have not gotten to work is the systemd service. Seems to not start the database services that where created. Right now I change the N key to Y in oratab to get around this.

**Comment by oravirt** [comment]
Yeah. The autostart came in as part of a pr (d61f44f19a80919d0acb4f5fc1330539630cc1e6), and it uses the dbstart/dbshut scripts which relies on the N being a Y in oratab, but that commit doesn't actually change it accordingly.  
It has to be fixed (should be a simple lineinfile I think)
