### ISSUE TITLE
Is there any module manual?

### ISSUE THREAD

**Issue by kodiss** [oravirt/ansible-oracle#316]
I read anything in github.
But i can't find the detail manual for using this collection.
I want to install the database using this collection.
Is there anyone who can help?

**Comment by kodiss** [comment]
I want to find the detail manual like ansible docs.
(https://docs.ansible.com/ansible/2.9/modules/list_of_all_modules.html)

Thank you!

**Comment by Rendanic** [comment]
There is a beginner guide:
https://github.com/oravirt/ansible-oracle/blob/master/doc/guides/beginner.adoc

I am not sure if that's what you are asking for.

The documentation of the inventory is on the todo list for this year. It is highly recommended but takes time to complete.

Regards
Thorsten
