### ISSUE TITLE
orahost-storage raw disk support

### ISSUE THREAD

**Issue by lndevnull** [oravirt/ansible-oracle#34]
This is more of a "discussion/feature request than an issue but I'd like to look at the possibility of having the option to label RAW disk devices as ASM disks opposed to requiring partitions.  The primary reason is online resizing (expanding) ASM DG's is so much easier without dealing with partitions.

It looks like part of the work is done with committing of the new partition_devices var and have plans too expand upon this when I have time.

**Comment by oravirt** [comment]
Hi,

Yes, I'm actually already working on having that possibility so it will be supported shortly.

regards
/M

**Comment by oravirt** [comment]
This should be solved by 4e7ca420ef5270ec20d368fe1d3a1f9448b54cbc.

The basic funtionality is there, and it works with asmlib but it's not entirely there if you want to use udev (yet). Haven't had time to fix that yet.

**Comment by Rendanic** [comment]
Is that tested? oracleasm is not able to create a label on the block device itself. This was possible in the begining of oracleasm. 
One major reason for this change is, that all ASM-Disks of a diskgroup must have the same size. Another point is safety. It is clear that a disk with a partition is still in use and can't be reused for a filesystem. Most admin do not know, that 'blkid' will show a list of used devices with type.

**Comment by oravirt** [comment]
Do you mean using udev? Or just in general?

Like you said, oracleasm can't create a label on the actual blockdevice, but if you're using e.g dm-multipath it works. Whether or not it's a good idea, I'll leave for the user to decide.

The default will create partitions and use them though.

**Comment by Rendanic** [comment]
Look the following example:
    [root@oradb04 ~]# oracleasm createdisk testdisk1 /dev/sde
    Device "/dev/sde" is not a partition

This was possible with old versions of oracleasm.

**Comment by oravirt** [comment]
Yes, that’s what I said.
Unless you’ve layered e.g dm-multipath on top of the block device it doesn’t work

**Comment by Rendanic** [comment]
Solved with last comment from Mike.
