### ISSUE TITLE
wrong gid of backupdba

### ISSUE THREAD

**Issue by markuman** [oravirt/ansible-oracle#368]
https://github.com/oravirt/ansible-oracle/blob/535c2643da70f4e3454a8940f764a9f2d281ac8c/roles/orahost/defaults/main.yml#L14C13-L14C22

it must be 54324, not 54323

https://docs.oracle.com/en/database/oracle/oracle-database/12.2/ssdbi/required-operating-system-groups-and-users.html#GUID-EBE883F8-5692-43C6-9CEB-2953C2E2837D

**Comment by markuman** [comment]
and `oper` gid is 54323 and not 54324

**Comment by Rendanic** [comment]
Hi Markus,
the `gid`s in the documentation from oracle are not mandatory. They could be changed per installation.

You could set your own `gid`s in your installation to match the documentation but there is no need for itthat.

_Changing the `gid`s in `ansible-oracle` is a breaking change for existing installations._


Kind Regards
Thorsten
