### ISSUE TITLE
Break out passwords to use external file

### ISSUE THREAD

**Issue by oravirt** [oravirt/ansible-oracle#38]
Password management will be broken out, such that it can be put in a separate file that easily can be vaulted.

**Comment by oravirt** [comment]
WIP

**Comment by oravirt** [comment]
So, I've finally had time to fix this, and this is how it will work.

This change will make it possible to break out the passwords to an external file that can be easily encrypted, and is broken up into a GI part & a DB part.
The default passwords (and the example structure) are part of 
```
oraswgi-install/defaults/main.yml
oradb-create/defaults/main.yml
```
and not broken out in an external passwords.yml. But that is what you would do if you wanted to encrypt the passwords using Vault.

GI:
```
- default_gipass: This will be the default password if either of the 2 following are not defined
- sysasmpassword: Password for the sysasm user
- asmmonitorpassword:  Password for the asmsnmp account
```

DB:
`- default_dbpass: This will be the default/fallback password if DB specific passwords are not defined`

The following is the password lookup-structure that can be defined per database:
```
dbpasswords:
       db1:                    <- This defines the passwords for the db1 database. If omitted all passwords falls back to default_dbpass
         sys: Oracle_456
         system: Oracle_456
         dbsnmp: Oracle_456
         pdbadmin: Oracle_456
       db2:                    <- This defines the passwords for the db2 database. If omitted all passwords falls back to default_dbpass
         sys: Oracle_789
         dbsnmp: Oracle_789
         pdbadmin: Oracle_789
```
In the above example, since `system` is missing from the `db2` database, the password will fallback to whatever `default_dbpass` is set to.

At the moment, this only deals with users that gets created as part of creating a new DB with dbca (`sys/system/dbsnmp etc`). 
It will also work for user-defined users/schemas in both (c)dbs & pdbs

**Comment by Rendanic** [comment]
The idea looks very good, but hopefully it will not break existing configurations.
Could you change the file permissions for the responsefiles with passwords to 600?

**Comment by oravirt** [comment]
Thank you!
Well, 2 variables are being removed so there is always a possibility that something goes wrong, but  as long as you just port your existing passwords to the new structure you should be fine. I've tested this pretty thoroughly so hopefully it should not be any problems.

I've also kept the `oracle_password`  around just as a precaution (and I just set it to the same as `default_gipass`), but that is just temporary. None of the old variables are being used anywhere anymore, so it shouldn't really be a problem.

re: permissions, sure.

I'm also (probably) adding a task (configurable of course) task that scrubs the passwords from the reponsefiles after a successful installation/creation of database

**Comment by Rendanic** [comment]
Could you add a devel branch to the project and pull the changes to give us a preview?
I think there is a solution for old setups.

new variable (Default False): `old_oracle_password: false `

`{% old_oracle_password %] Default values in oracle_passwords is changed to oracle_password{% endif %}`

Old configurations only need to add `old_oracle_password: true` in 'all' to enable the old variables.
Everything is done in 'defaults/main.yml' and it's possible to remove the exception in a future release.
An assert information that old_oracle_password is true and dbpasswords were replced by oracle_password.

**Comment by oravirt** [comment]
Yes, I will push this branch before going live

Last night, I added this as a interim solution for the old password structure

```
default_gipass: "{% if oracle_password is defined %}{{ oracle_password }}{% else %}Oracle123{% endif%}" # The check for the old passwords are there for backwards compatibility and only temporary, will be removed
sysasmpassword: "{% if oracle_password is defined %}{{ oracle_password }}{% else %}Oracle123{% endif%}" # The check for the old passwords are there for backwards compatibility and only temporary, will be removed
asmmonitorpassword: "{% if oracle_password is defined %}{{ oracle_password }}{% else %}Oracle123{% endif%}" # The check for the old passwords are there for backwards compatibility and only temporary, will be removed
default_dbpass: "{% if item.0.oracle_db_passwd is defined %}{{ item.0.oracle_db_passwd}}{% else %}Oracle123{% endif%}" # The check for the old passwords are there for backwards compatibility and only temporary, will be removed
```


But this will only be for the default passwords and only in  `defaults/main.yml`. As soon as you start using the new lookup structure (or explicitly set the default_db/gipass or sysasmpassword/asmmonitorpassword), that takes precedence

**Comment by oravirt** [comment]
Pushed changes, branch is called password

**Comment by oravirt** [comment]
Solved by https://github.com/oravirt/ansible-oracle/commit/6238ac93c8cc2f734df1345ed14c1defa2f1f9ed
