### ISSUE TITLE
orahost: RedHat 6 disable transparent hugepage issue

### ISSUE THREAD

**Issue by aetile** [oravirt/ansible-oracle#39]
Hello,

I have this error message when attempting a dry run on a fresh RHEL 6.8 install:

TASK [orahost : Disable Transparent Hugepages (in grub.conf)] *****************************************************************
task path: /home/arnaw/ansible-oracle/roles/orahost/tasks/RedHat-6.yml:8

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Exception: Error while setting attributes: /usr/bin/chattr: Clearing extent flag not supported on /etc/grub.conf.11711.2017-10-22@11:47:14~
failed: [ansible-node1] (item=0) => {"changed": false, "details": "Error while setting attributes: /usr/bin/chattr: Clearing extent flag not supported on /etc/grub.conf.11711.2017-10-22@11:47:14~\n", "failed": true, "gid": 0, "group": "root", "item": "0", "mode": "0600", "msg": "chattr failed", "owner": "root", "path": "/etc/grub.conf.11711.2017-10-22@11:47:14~", "secontext": "system_u:object_r:etc_t:s0", "size": 839, "state": "file", "uid": 0}

I have no idea if lineinfile module makes use of the shell chattr command in its code, maybe you could try the replace module instead, which basically do the same, for example by replacing "quiet" in kernel line with "quiet transparent_hupage=never"? 

For me it worked when I replaced the lineinfile with the following:

replace: dest=/etc/grub.conf regexp='quiet' replace='quiet transparent_hugepage=never'

Not a clean solution of course, just an idea for the right regexp ;)
Regards,

**Comment by oravirt** [comment]
Hi,
I have tried to re-produce this on RHEL, Centos, Oracle Linux, Scientific Linux (different 6.x versions) but I can't get it to re-produce, it always works.
So, I'm not sure why this is is happening on your system, but given the other problem (https://github.com/oravirt/ansible-oracle/issues/40) you've reported (which I also can't reproduce, on any of the above platforms), I suspect this is more an issue with your specific system than anything else.

**Comment by oravirt** [comment]
Hi,

Just updated Ansible to 2.4.1 and was able to re-produce the error (on Centos 6.9). 
However, I fixed it by changing the file operated on to /boot/grub/grub.conf instead of the link (etc/grub.conf)

**Comment by aetile** [comment]
Hi,

After investigating, the chattr issue was caused by a messed selinux conf file.

**Comment by oravirt** [comment]
Just for reference:
Ansible version: 2.4.1
OS: rhel/centos 6.7/8/9

I reproduced this error with selinux completely disabled, but was trying to operate on the link (/etc/grub.conf), instead of the actual file (/boot/grub/grub.conf). When changing the actual file, the error went away.

On all other versions of Ansible, this worked fine
