### ISSUE TITLE
TASK [oraswdb-install : Check if DB-server is already installed] *************** fatal: [xxx.xx.xx.xx]: FAILED! => {"failed": true, "msg": "'unicode object' has no attribute 'oracle_version_db'"}

### ISSUE THREAD

**Issue by trvsmtchll** [oravirt/ansible-oracle#4]
Hello,
I'm trying to run this on a single host using the following:
---
- name: Host configuration
hosts: xxx.xx.xx.xx
user: centos
sudo: yes
roles:
- common
- orahost

- name: Database Server Installation
hosts: xxx.xx.xx.xx
user: centos
sudo: yes
roles:
- oraswdb-install

It runs fine until the oraswdb-role then has this error. 
TASK [oraswdb-install : Check if DB-server is already installed] *************** fatal: [xxx.xx.xx.xx]: FAILED! => {"failed": true, "msg": "'unicode object' has no attribute 'oracle_version_db'"}

Can you share an example orafs variables file please?
It's referenced in single-instance-db-on-fs.yml.

**Comment by oravirt** [comment]
Hi,

Yeah, the 'hosts: orafs' is something from my lab-environment that I removed. I'll set up a new group_vars/orafs as an example. 
But you basically don't have to change anything if what you want is a 12.1.0.2 DB (which is the default) apart from setting up your inventory and changing the 'hosts: xxxx' in the single-instance-db-on-fs.yml playbook to match the inventory. 

In your play, are you only referencing the roles you mentioned here?
Have you set up group_vars/host_vars for this playbook?

**Comment by trvsmtchll** [comment]
Thanks I made a copy of one of the group_vars/host_vars made sure it had all of the variables in for oracle_databases:. Then created a group with the same name in a scratch inventory file and referenced it when running the playbook that seemed to get past the issue I was having.Is there any harm adding a task in oraswdb-install to start a listener running out of the new db $OH wondering why that isn't there.

**Comment by oravirt** [comment]
Hi,

Good that you got it working!
There is no problem adding that step yourself. I kind of forgot about it as I usually run my DB's with GI installed as well. But, I do have a fix for that, that I haven't pushed yet.

I'll also update the oraswdb-install/defaults/main.yml with the oracle_databases list

**Comment by trvsmtchll** [comment]
Thank you!
