### ISSUE TITLE
libaio i686 is missing at listener/database creation

### ISSUE THREAD

**Issue by aetile** [oravirt/ansible-oracle#41]
Before manually installing libaio 32 bits I get the following error when running netca or dbca:

TASK [oradb-create : Create database(s)] ************************************************************************************
failed: [ansible-node1] ...
...
oracle.sysman.assistants.dbca.Dbca.main(Dbca.java:189)"], "stdout": "UnsatisfiedLinkError exception loading native library: njni11\njava.lang.UnsatisfiedLinkError: /u01/app/oracle/11.2.0.4/db1/lib/libnjni11.so: libaio.so.1: cannot open shared object file: No such file or directory", "stdout_lines": ["UnsatisfiedLinkError exception loading native library: njni11", "java.lang.UnsatisfiedLinkError: /u01/app/oracle/11.2.0.4/db1/lib/libnjni11.so: libaio.so.1: cannot open shared object file: No such file or directory"]}

After installing the missing package it runs OK.

**Comment by oravirt** [comment]
Sure, I'll add it to the default packages, but I don't really understand what is going on with your system ;-) 
I've used this on at least 50 different rhel6 (6.5 to 6.9) installs, and I've never seen the issues you're having. It's really weird...

**Comment by oravirt** [comment]
Fixed with d005460f1cbb91d2ee71d92a5400934c09b51ee6

**Comment by aetile** [comment]
Thanks.

**Comment by aetile** [comment]
Thanks
