### ISSUE TITLE
No way to change FRA destination with DBCA

### ISSUE THREAD

**Issue by aetile** [oravirt/ansible-oracle#42]
Despite setting the variable oracle_reco_dir_fs: /u01/fra, recovery area always end up in $ORACLE_BASE/fast_recovery_area when using DBCA.

I still didn't find a workaround except by using custom scripts with CREATE DATABASE. This is a minor issue but needs to be addressed anyway. Maybe I missed something while repeatedly reading Oracle official docs  ;)

**Comment by oravirt** [comment]
See https://github.com/oravirt/ansible-oracle/issues/24

**Comment by oravirt** [comment]
I always customize the installation using these modules: https://github.com/oravirt/ansible-oracle-modules

**Comment by oravirt** [comment]
Also, you should use datafile_dest/recoveryfile_dest instead of oracle_<reco/dbf>_dir_fs

**Comment by aetile** [comment]
OK. So I'm closing this ticket.
