### ISSUE TITLE
Ideas: customize redolog and controlfile dest

### ISSUE THREAD

**Issue by aetile** [oravirt/ansible-oracle#44]
Hello,

When using DBCA there is no way to customize the number of redolog groups and file destination, same with controlfiles.

- 3 redolog groups are created in datafile_dest
- Only 2 controlfiles are created, one in datafile_dest, the other in recovery_dest

Doing it in a SQL script after db creation is tricky: redo group must be unused to change file location and if controfiles are stored in ASM you must use RMAN to add one.

So if anyone has ideas. I was thinking maybe to give the possibility to execute a custom SQL script given as a new group/host var after db creation.

**Comment by aetile** [comment]
I propose to make TEMPLATENAME = "General_Purpose.dbc" customizable in oradb-create role DBCA templates. You only need to add one variable :)

**Comment by oravirt** [comment]
Agreed. I've been meaning to do that for a long time.
https://github.com/oravirt/ansible-oracle/commit/0de1d65a4614f24c952bc2cb6d8b4d26d4d6849d

**Comment by aetile** [comment]
Thanks a lot.
