### ISSUE TITLE
Disable transparent hugepages by kernel cmdline

### ISSUE THREAD

**Issue by ThiloSolbrig** [oravirt/ansible-oracle#459]
* Transparent hugepages are actually disabled dynamically, featuring boot scripts
* Provide an enhancement to disable transparent hugepages by kernel cmdline, which is more robust and up-to-date (e.g. this could be secured by bootloader password and thus made more difficult to become overridden than bootup scripts)
Implemented by https://github.com/oravirt/ansible-oracle/pull/460/

**Comment by Rendanic** [comment]
fixed by #460
