### ISSUE TITLE
Trying to understand oracle_home_db variable

### ISSUE THREAD

**Issue by firastahir** [oravirt/ansible-oracle#47]
I'm a newbie to ansible and trying so hard to understand the way you configured oracle_home_db variable in the oraswdb-install role but it's not clear to me, can you please explain why you did not put a static value to this variable same as you did with oracle_base and oracle_inventory_loc?

oracle_home_db: "{% if item.0 is defined %}{% if item.0.oracle_home is defined %}{{ item.0.oracle_home}}{% else %}{{ oracle_base }}/{{ item.0.oracle_version_db }}/{{ item.0.home }}{% endif %}{% else %}{% if item.oracle_home is defined %}{{ item.oracle_home }}{% else %}{{ oracle_base }}/{{ item.oracle_version_db }}/{{ item.home }}{% endif %}{% endif %}"

Thank you

**Comment by oravirt** [comment]
Hi,

The main reason for this variable not being static, is that you could have more than one database and those databases can have different oracle_homes.

By default the oracle_home is oracle_base/oracle_version/home-name
  oracle_databases:
          - home: db1         
             oracle_version_db: 12.2.0.1 
So in this case ORACLE_HOME would be **/u01/app/oracle/12.2.0.1/db1**

However, if you have a different naming standard you can override the default by doing this:
 oracle_databases:
          - home: db1
             **oracle_home: /path/to/oracle/home**         
             oracle_version_db: 12.2.0.1 
And in this case oracle_home would be **/path/to/oracle/home**

**Comment by firastahir** [comment]
It's clear now, thank you very much!

Best
Firas
