### ISSUE TITLE
screen package for RHEL8 and higher

### ISSUE THREAD

**Issue by talek** [oravirt/ansible-oracle#495]
Hello,

Based on "[The `screen` package is deprecated and not included in RHEL8.0.0](https://access.redhat.com/solutions/4136481)" note, does it make sense to get rid of the screen package from `common_packages_el[8-9]` lists defined in the `common` role?

I'd like to avoid registering EPEL just for this package.

Thanks!

Regards,
Alec

**Comment by Rendanic** [comment]
Hi Alec,
I personalle do not use screen.
We could remove it from the defaults.

Kind Regards
Thorsten
