### ISSUE TITLE
Compatibility against current Versions of Ansible

### ISSUE THREAD

**Issue by Rendanic** [oravirt/ansible-oracle#6]
I am working on a lot of enhancements in ansible-oracle and doing this with Ansible 2.1.
I never tested my changes against older versions.

Is there a good reasong for sticking to an old version?

**Comment by oravirt** [comment]
Not really.

So far it's been backwards-compatible just by default, but I'll probably create a release that I know works with the latest 1.9 release and then leave it at that. If one can't go above 1.9 then that is the release one would have to use.

I'm only using 2.1 myself these days anyway.

**Comment by Rendanic** [comment]
i found a strange problem with ansible-oracle and Ansible 2.1.3.0.
https://github.com/ansible/ansible/issues/16956
> ansible behaviour inventory variables not being picked up from group_vars in 2.1.1 #16956

It tool me a lot of time to find this bug, because I used Ansible 1.9 and switched to 2.1 and hit this problem. i think ansible-oracle should change the structure to the new format, because this is much better then the old structure and it is a change in behavior of Ansible...

Kind Regards
Thorsten Bruhns

**Comment by oravirt** [comment]
I haven't had time to look at this (or the referenced issue) yet. I'll check into it as soon as I can though.

But just to clarify: After you upgraded to 2.1.3.0, did it stop working (as in variables are not being picked up) using the current directory structure or are you using a different structure?

**Comment by Rendanic** [comment]
Hallo Mikael,
you need to use a different structure in 2.1.3. This is due to a change in behavior of Ansible, which takes affect in 2.1. It was introduced in a later version and the old structure with group_vars and host_vars is deprecated since some versions. (Can't find the information at the moment.)

I think it is a good idea, when group_vars and host_vars are moved to the inventory directory. It makes ansible-oracle much cleaner and better to use in new projects, because only the inventory directory must be cleaned and build from scratch for the project.

I only use the new structure, because of the massive amount of time to find this new behavior...

**Comment by herebebogans** [comment]
Hi,
First off - this is an awesome role and has saved our team a lot of time.

A lot of the Jinja when: conditionals are now syntax errors in Ansible ~> 2.2. Also a number of tasks do become: to an unpriveleged user which causes issues

http://docs.ansible.com/ansible/latest/become.html#becoming-an-unprivileged-user

Enabling `allow_world_readable_tmpfiles=True` in `ansible.cfg` is a workaround.

Are there any plans to update the role to be compatible with latest Ansible - or will you take PR's?

**Comment by oravirt** [comment]
HI,
First of all - Thank you!
 
Yes, I'm in the process of fixing those Jinja problems (but on vacation right now). 
However, PR's are most welcome!

**Comment by oravirt** [comment]
Just a clarification: I'm sorting out the obvious stuff in all the tasks, i.e remove {{}} around variables in the conditionals, but I haven't yet looked into how to deal with variables that use jinja (like if-else type stuff), and then those variable are used in a conditional.

**Comment by oravirt** [comment]
Re: the variable stuff. It looks like setting a fact with the same name as the variable gets rid of the warning at least, so could be a way forward.
I'll explore this in a bit more detail

**Comment by oravirt** [comment]
I'm tracking the Jinja2 deprecation stuff in https://github.com/oravirt/ansible-oracle/issues/37

**Comment by oravirt** [comment]
The 2.3 & Jinja issues should be fixed by https://github.com/oravirt/ansible-oracle/commit/17720e1d5879d17e1e8e699da648ef203b4c8f83

**Comment by Rendanic** [comment]
ansible-oracle is still working with version 2.4.2.0. 
This issue is fixed for me.
