### ISSUE TITLE
Deal with issues from #59

### ISSUE THREAD

**Issue by oravirt** [oravirt/ansible-oracle#61]
This will track fixes for #59

**Comment by oravirt** [comment]
https://github.com/oravirt/ansible-oracle/commit/19cf90839190f4cd19a1dfcca0b33657cd2e2150 should fix the issues in #59

**Comment by onenessboy** [comment]
Thank you so much ...I shall test out. Do you have any plans to write up playbook  for OEM as well (just out of curiosity )

**Comment by oravirt** [comment]
Great!
Re: OEM - I have one that works, it's about 3 years old and needs to be re-factored quite a bit before I release it.

**Comment by onenessboy** [comment]
Wow Great news out OEM.. Would be glad to see that soon..just curious about... Thanks for all help

**Comment by onenessboy** [comment]
Hi

Hope you are doing good..

sorry i was bit late in getting good infrastructure with bigger VM to try this...

I have used latest code clone which you have fixed for issues mentioned in #61 

The below is error

TASK [orahost : Install packages required by Oracle on OL/RHEL] **************************************************************************************
failed: [1.2.3.202] (item=[u'libselinux-python', u'procps', u'psmisc', u'module-init-tools', u'ethtool', u'bc', u'bind-utils', u'nfs-utils', u'util-linux-ng', u'xorg-x11-utils', u'xorg-x11-xauth', u'binutils', u'compat-libstdc++-33', u'compat-libstdc++-33.i686', u'unixODBC-devel', u'unixODBC-devel.i686', u'gcc', u'gcc-c++', u'glibc', u'glibc.i686', u'glibc-devel', u'glibc-devel.i686', u'libaio', u'libaio-devel', u'libaio.i686', u'libaio-devel.i686', u'libgcc', u'libgcc.i686', u'libstdc++', u'libstdc++-devel', u'libstdc++.i686', u'libstdc++-devel.i686', u'make', u'sysstat', u'openssh-clients', u'compat-libcap1', u'xorg-x11-xauth', u'xorg-x11-xinit', u'libXtst', u'xdpyinfo', u'xterm', u'xsetroot', u'libXp', u'libXt', u'libXtst', u'ntp', u'ksh', u'lvm2', u'xfsprogs', u'btrfs-progs', u'parted', u'nc', u'smartmontools', u'elfutils-libelf-devel.i686', u'elfutils-libelf-devel']) => {"changed": false, "item": ["libselinux-python", "procps", "psmisc", "module-init-tools", "ethtool", "bc", "bind-utils", "nfs-utils", "util-linux-ng", "xorg-x11-utils", "xorg-x11-xauth", "binutils", "compat-libstdc++-33", "compat-libstdc++-33.i686", "unixODBC-devel", "unixODBC-devel.i686", "gcc", "gcc-c++", "glibc", "glibc.i686", "glibc-devel", "glibc-devel.i686", "libaio", "libaio-devel", "libaio.i686", "libaio-devel.i686", "libgcc", "libgcc.i686", "libstdc++", "libstdc++-devel", "libstdc++.i686", "libstdc++-devel.i686", "make", "sysstat", "openssh-clients", "compat-libcap1", "xorg-x11-xauth", "xorg-x11-xinit", "libXtst", "xdpyinfo", "xterm", "xsetroot", "libXp", "libXt", "libXtst", "ntp", "ksh", "lvm2", "xfsprogs", "btrfs-progs", "parted", "nc", "smartmontools", "elfutils-libelf-devel.i686", "elfutils-libelf-devel"], "msg": "Failure talking to yum: failure: repodata/repomd.xml from rhel-7-server-beta-debug-rpms: [Errno 256] No more mirrors to try.\nhttps://cdn.redhat.com/content/beta/rhel/server/7/x86_64/debug/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden"}

Can you please help

**Comment by Rendanic** [comment]
The installation with OL7 and OL8 is tested and working. Older releases of OL are not tested anymore, due to lack of free patches from Redhat and Oracle.
