### ISSUE TITLE
asm_diskgroups is undefined

### ISSUE THREAD

**Issue by patriziobassi** [oravirt/ansible-oracle#62]
orahost-storage in the 
task name: ASM-storage | Create device to label mappings for asm

loops on with_items: "{{asm_diskgroups}}" which is undefined because it's commented out in its default.yaml file.

**Comment by oravirt** [comment]
Should be fixed by https://github.com/oravirt/ansible-oracle/commit/ed2602ac3c67f16acd8c3244b04a5b385b186662
