### ISSUE TITLE
oraswgi-install missing remote_src attributes

### ISSUE THREAD

**Issue by patriziobassi** [oravirt/ansible-oracle#63]
in oraswgi-install role, the main.yaml contains a broken task

- name: Copy oracle installfiles to server (GI) (local)
    copy: src={{ oracle_sw_source_local }}/{{ item.filename }} dest={{ oracle_stage }} mode=775

is missing remote_src=yes otherwise it looks for the zip file in the ansible manager machine.

**Comment by oravirt** [comment]
No, it is not broken. The point of that task is to copy files from the control-machine to the db-host(s)
