### ISSUE TITLE
oraswdb-install always re-downloads and unpacks zip sw even if db is already installed

### ISSUE THREAD

**Issue by patriziobassi** [oravirt/ansible-oracle#64]
Tasks:
Transfer oracle installfiles to server (www)
Transfer oracle installfiles to server (local)
Extract files to stage-area
Extract files to stage-area (from remote location)

should check checkdbswinstall.[item#].stdout != 1 in the when statement

**Comment by oravirt** [comment]
Yes, this is being addressed by the re-factor. 
It will not use the stdout register though

**Comment by Rendanic** [comment]
should be fixed.
