### ISSUE TITLE
replace autofs for mount -t nfs

### ISSUE THREAD

**Issue by Rendanic** [oravirt/ansible-oracle#67]
I prefer installations with a NFS-Share for installation media and rman Backups.
What do you think about removing the tasks `Mount nfs share with installation media` after enabling the autofs?

I could  create a PR for adding and enabling autofs. The mounts could be removed during the refactoring.

**Comment by oravirt** [comment]
I don't want to remove the task (at least not yet), since I know it is being used.

But if you want to add autofs functionality, go ahead. The autofs package is part of  'common packages' as of https://github.com/oravirt/ansible-oracle/commit/cd66e5b0cedeb2bf169b7c90a75e04ca3f07c78c.

**Comment by Rendanic** [comment]
#269 add tasks to `orasw_meta`.
The new tasks makes the handling of mount/umound of installation media much easier.
No real need to use autofs for this and we had a customer which didn't allow to use autofs on the machines.
