### ISSUE TITLE
Making ansible-oracle license compliant

### ISSUE THREAD

**Issue by Rendanic** [oravirt/ansible-oracle#7]
We really need a solution for creating Database who are license compliant.
There are a couple of problems with the current implementation of creating databases. The biggest issue is, that there is no way to configure the options inside a database when creating Multitenant Databases without using sql-scripts.

I plan to replace the current funtions with a set of sql-Statements as template. 
Is it fine to do it and sending a pull request to you?

**Comment by oravirt** [comment]
yeah, I was going to redo/expand the dbcreate role anyway so sure, go ahead.
But I'd rather you didn't replace the current way of doing it as it still has its place. 
So add your stuff as an option and make it configurable.

First of all I'm externalizing the TEMPLATENAME parameter, and then I'm looking into using a custom template when creating the db and have like an db_options list where you have a true/false choice for each option, but there is not enough hours in the day atm.

I really should start using the issue-tracker....

**Comment by Rendanic** [comment]
I tried with a variable for TEMPLATENAME and realized in MyOracleSupport that there is no way to do it license compliant. You need to create SQL-script for create database, modify them and finaly start the script.

I try to create a solution with sql template files in ansible, transfer them to the destination host and execute them. That's a total new way but the only one in Multitenant when only a subset of database options are needed/allowed.

**Comment by Rendanic** [comment]
I wrote some templatefiles in Ansible and I am able to create a database from it. It is not completed, because the dbca does a lot of addional stuff, that must be done with script...
That is the good news, but I still have a really bad information:

We need to apply a Patch for Bug 20501388 on top of 12.1.0.2. Otherwise we are not able to create the data dictionary from scripts.

I stop the development at this point, until we have a solution for installing PSUs on top of Database-Homes.

**Comment by oravirt** [comment]
Ok - I'm working on a oraswdb-opatch role that will apply patches on database homes

**Comment by aetile** [comment]
Hello,

Any update on this topic? I need this urgently as well.
For info I'm using customized DBCA scripts at work for 11.2 and 12.2 versions.

**Comment by Rendanic** [comment]
I am working on this issue but there are other points who needs to be done before.

**Comment by Rendanic** [comment]
PR #69 is the first step for 12.2.0.1. This is only for the executable. Some work is needed for the Data-Dictionary as well.

**Comment by Rendanic** [comment]
The implementation of the new inventory structure removed the features from #88.
This has been fixed with #109. The support for 18c has been added as well.

We can close thiss issue after PR #109 has been merged.
