### ISSUE TITLE
SSH Equivalence for root

### ISSUE THREAD

**Issue by akerrai** [oravirt/ansible-oracle#77]
Hello,

Is there away to configure SSH equivalence for the user, we're using root at the moment, as part of the common tasks?

**Comment by oravirt** [comment]
Hi,
I guess you mean between the control-machine and your targets?
I could add an extra role which can be toggle-included, where you define the user(s) you want to either create or add keys for?

**Comment by akerrai** [comment]
That would be great, would mean you could effectively run this from the get-go limited initial setup on the targets

**Comment by akerrai** [comment]
I also hit this error:
 yum: Cannot retrieve metalink for repository: epel/x86_64

I assume that is something not setup right on the target side with the repo?

**Comment by oravirt** [comment]
Sorry about the late answer, but yes - something is iffy at the target

**Comment by akerrai** [comment]
No worries, thanks so much for continuing to answer the benign questions...

I fixed the yum issue, it needed "yum update" running on the host to pull everything down.  However now the playbook just seems to sit there on this task:

TASK [common : Install common packages OL/RHEL] ***************************************************************************************************************

I've checked over on the host can see python running but it doesn't look like yum has been called:
[root@OL7-ANS-TST yum.repos.d]# ps -ef |grep yum
root      3245  2887  0 16:20 pts/1    00:00:00 /bin/sh -c sudo -H -S -n -u root /bin/sh -c 'echo BECOME-SUCCESS-vcapokvxqiqsqjmxzvdfvavmloymxpsa; http_proxy=http://proxy.logica.com:80 use_proxy=True /usr/bin/python /root/.ansible/tmp/ansible-tmp-1528730451.19-66823140883058/yum.py' && sleep 0
root      3254  3245  0 16:20 pts/1    00:00:00 sudo -H -S -n -u root /bin/sh -c echo BECOME-SUCCESS-vcapokvxqiqsqjmxzvdfvavmloymxpsa; http_proxy=http://proxy.logica.com:80 use_proxy=True /usr/bin/python /root/.ansible/tmp/ansible-tmp-1528730451.19-66823140883058/yum.py
root      3255  3254  0 16:20 pts/1    00:00:00 /bin/sh -c echo BECOME-SUCCESS-vcapokvxqiqsqjmxzvdfvavmloymxpsa; http_proxy=http://proxy.logica.com:80 use_proxy=True /usr/bin/python /root/.ansible/tmp/ansible-tmp-1528730451.19-66823140883058/yum.py
root      3256  3255  0 16:20 pts/1    00:00:00 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1528730451.19-66823140883058/yum.py
root      3257  3256  0 16:20 pts/1    00:00:00 /usr/bin/python /tmp/ansible_KFi1is/ansible_module_yum.py
root      3264  1554  0 16:24 pts/0    00:00:00 grep --color=auto yum
[root@OL7-ANS-TST yum.repos.d]#

I'm not sure what is causing the blocker, I've run the python script manually that just sits there also

**Comment by akerrai** [comment]
Actually this time it bombed out:
TASK [common : Install common packages OL/RHEL] *********************************************************************************************************************************************************************************************
fatal: [OL7-ANS-TST.local]: FAILED! => {"changed": false, "msg": "Failure talking to yum: failure: repodata/repomd.xml from ol7_addons: [Errno 256] No more mirrors to try.\nhttps://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64/repodata/repomd.xml: [Errno 12] Timeout on https://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')\nhttps://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64/repodata/repomd.xml: [Errno 12] Timeout on https://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')\nhttps://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64/repodata/repomd.xml: [Errno 12] Timeout on https://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30002 milliseconds')\nhttps://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64/repodata/repomd.xml: [Errno 12] Timeout on https://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')\nhttps://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64/repodata/repomd.xml: [Errno 12] Timeout on https://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30002 milliseconds')\nhttps://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64/repodata/repomd.xml: [Errno 12] Timeout on https://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')\nhttps://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64/repodata/repomd.xml: [Errno 12] Timeout on https://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')\nhttps://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64/repodata/repomd.xml: [Errno 12] Timeout on https://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')\nhttps://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64/repodata/repomd.xml: [Errno 12] Timeout on https://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')\nhttps://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64/repodata/repomd.xml: [Errno 12] Timeout on https://yum.oracle.com/repo/OracleLinux/OL7/addons/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')"}


I think it's a proxy issue although I've set the following:
  - name: Install common packages OL/RHEL
    yum: name={{ common_packages }} state=installed
    environment:
     http_proxy: http://proxy.logica.com:80
     use_proxy: yes
    when: install_os_packages and ansible_os_family == 'RedHat'
    tags:
      - commonpackages

**Comment by akerrai** [comment]
Okay I've sorted the yum issues out, it was a combination of running yum update directly on the host for the first time and then proxy settings etc.

Now it's falling at this:

TASK [orahost : Asmlib | Enable and start Oracle Asmlib] ************************************************************************************************************************************************************************************
fatal: [OL7-ANS-TST.local]: FAILED! => {"changed": false, "msg": "Could not find the requested service oracleasm: host"}
        to retry, use: --limit @/root/ansible-oracle/vbox-si-asm-install.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
OL7-ANS-TST.local          : ok=31   changed=25   unreachable=0    failed=1

Doesn't look like oracleasm is there on the host.

**Comment by Rendanic** [comment]
The installation of Restart/GI with ASM was refactored for 19c or newer.
This should be fixed there. Older versions are not supported anymore.
