### ISSUE TITLE
oradb-create : Add dotprofile (2) : "AnsibleUndefinedVariable: 'dbh' is undefined"

### ISSUE THREAD

**Issue by akerrai** [oravirt/ansible-oracle#78]
I've tried to diagnose this, struggling to unfortunately:

TASK [oradb-create : Add dotprofile (2)] ****************************************************************************************************************************************************************************************************
failed: [OL7-ANS-TST.local] (item=[{u'tablespaces': [{u'name': u'blerghapp1_data', u'autoextend': True, u'state': u'present', u'next': u'5M', u'content': u'permanent', u'maxsize': u'500M', u'bigfile': True, u'size': u'10M'}], u'is_container': True, u'users': [{u'state': u'present', u'grants': [u'approle1'], u'default_tablespace': u'blerghapp1_data', u'schema': u'blerghapp1'}], u'roles': [{u'state': u'present', u'grants': [u'create session', u'create table', u'select any table', u'select any dictionary'], u'name': u'approle1'}], u'oracle_db_type': u'SI', u'oracle_database_type': u'MULTIPURPOSE', u'init_parameters': [{u'scope': u'both', u'state': u'present', u'name': u'db_recovery_file_dest_size', u'value': u'20G'}], u'oracle_db_name': u'blergh', u'datafile_dest': u'+DATA', u'redolog_size_in_mb': 100, u'state': u'present', u'oracle_edition': u'EE', u'oracle_db_mem_totalmb': 1024, u'oracle_version_db': u'12.2.0.1', u'recoveryfile_dest': u'+FRA', u'services': [{u'state': u'started', u'name': u'blerghapp1_service'}], u'home': u'db1', u'storage_type': u'ASM'}, {'_ansible_parsed': True, 'stderr_lines': [], u'cmd': u'ps -ef | grep -w "ora_pmon_blergh" |grep -v grep | sed \'s/^.*pmon_//g\'', u'end': u'2018-06-13 09:15:23.387528', '_ansible_no_log': False, u'stdout': u'blergh', '_ansible_item_result': True, u'changed': False, 'item': {u'tablespaces': [{u'name': u'blerghapp1_data', u'autoextend': True, u'state': u'present', u'bigfile': True, u'content': u'permanent', u'maxsize': u'500M', u'next': u'5M', u'size': u'10M'}], u'is_container': True, u'users': [{u'state': u'present', u'grants': [u'approle1'], u'default_tablespace': u'blerghapp1_data', u'schema': u'blerghapp1'}], u'roles': [{u'state': u'present', u'grants': [u'create session', u'create table', u'select any table', u'select any dictionary'], u'name': u'approle1'}], u'oracle_db_type': u'SI', u'oracle_database_type': u'MULTIPURPOSE', u'init_parameters': [{u'scope': u'both', u'state': u'present', u'name': u'db_recovery_file_dest_size', u'value': u'20G'}], u'oracle_db_name': u'blergh', u'datafile_dest': u'+DATA', u'redolog_size_in_mb': 100, u'state': u'present', u'oracle_edition': u'EE', u'oracle_db_mem_totalmb': 1024, u'home': u'db1', u'recoveryfile_dest': u'+FRA', u'services': [{u'state': u'started', u'name': u'blerghapp1_service'}], u'oracle_version_db': u'12.2.0.1', u'storage_type': u'ASM'}, u'delta': u'0:00:00.061656', u'stderr': u'', u'rc': 0, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u'ps -ef | grep -w "ora_pmon_blergh" |grep -v grep | sed \'s/^.*pmon_//g\'', u'removes': None, u'creates': None, u'chdir': None, u'stdin': None}}, 'stdout_lines': [u'blergh'], u'start': u'2018-06-13 09:15:23.325872', '_ansible_ignore_errors': None, 'failed': False}]) => {"changed": false, "item": [{"datafile_dest": "+DATA", "home": "db1", "init_parameters": [{"name": "db_recovery_file_dest_size", "scope": "both", "state": "present", "value": "20G"}], "is_container": true, "oracle_database_type": "MULTIPURPOSE", "oracle_db_mem_totalmb": 1024, "oracle_db_name": "blergh", "oracle_db_type": "SI", "oracle_edition": "EE", "oracle_version_db": "12.2.0.1", "recoveryfile_dest": "+FRA", "redolog_size_in_mb": 100, "roles": [{"grants": ["create session", "create table", "select any table", "select any dictionary"], "name": "approle1", "state": "present"}], "services": [{"name": "blerghapp1_service", "state": "started"}], "state": "present", "storage_type": "ASM", "tablespaces": [{"autoextend": true, "bigfile": true, "content": "permanent", "maxsize": "500M", "name": "blerghapp1_data", "next": "5M", "size": "10M", "state": "present"}], "users": [{"default_tablespace": "blerghapp1_data", "grants": ["approle1"], "schema": "blerghapp1", "state": "present"}]}, {"_ansible_ignore_errors": null, "_ansible_item_result": true, "_ansible_no_log": false, "_ansible_parsed": true, "changed": false, "cmd": "ps -ef | grep -w \"ora_pmon_blergh\" |grep -v grep | sed 's/^.*pmon_//g'", "delta": "0:00:00.061656", "end": "2018-06-13 09:15:23.387528", "failed": false, "invocation": {"module_args": {"_raw_params": "ps -ef | grep -w \"ora_pmon_blergh\" |grep -v grep | sed 's/^.*pmon_//g'", "_uses_shell": true, "chdir": null, "creates": null, "executable": null, "removes": null, "stdin": null, "warn": true}}, "item": {"datafile_dest": "+DATA", "home": "db1", "init_parameters": [{"name": "db_recovery_file_dest_size", "scope": "both", "state": "present", "value": "20G"}], "is_container": true, "oracle_database_type": "MULTIPURPOSE", "oracle_db_mem_totalmb": 1024, "oracle_db_name": "blergh", "oracle_db_type": "SI", "oracle_edition": "EE", "oracle_version_db": "12.2.0.1", "recoveryfile_dest": "+FRA", "redolog_size_in_mb": 100, "roles": [{"grants": ["create session", "create table", "select any table", "select any dictionary"], "name": "approle1", "state": "present"}], "services": [{"name": "blerghapp1_service", "state": "started"}], "state": "present", "storage_type": "ASM", "tablespaces": [{"autoextend": true, "bigfile": true, "content": "permanent", "maxsize": "500M", "name": "blerghapp1_data", "next": "5M", "size": "10M", "state": "present"}], "users": [{"default_tablespace": "blerghapp1_data", "grants": ["approle1"], "schema": "blerghapp1", "state": "present"}]}, "rc": 0, "start": "2018-06-13 09:15:23.325872", "stderr": "", "stderr_lines": [], "stdout": "blergh", "stdout_lines": ["blergh"]}], "msg": "AnsibleUndefinedVariable: 'dbh' is undefined"}

**Comment by oravirt** [comment]
Can you show me the playbook?
I think you have to swap out the `oradb-create` (which is deprecated) role for `oradb-manage-db`

**Comment by akerrai** [comment]
Ah I was using the:
vbox-si-asm-install.yml

---
- name: Host configuration
  hosts: vbox-si-asm
  user: root
  become: yes
  roles:
     - common
     - orahost
     - orahost-storage
  environment:
     http_proxy: http://proxy.logica.com:80
     https_proxy: http://proxy.logica.com:80

- name: Oracle Grid Infrastructure installation
  hosts: vbox-si-asm
  user: root
  become: yes
  roles:
     - oraswgi-install

- name: ASM Diskgroup configuration
  hosts: vbox-si-asm
  user: root
  become: yes
  roles:
      - oraasm-createdg

- name: Database Server Installation & Database Creation
  hosts: vbox-si-asm
  user: root
  become: yes
  roles:
      - oraswdb-install
      - oradb-create

#- name: Customize database(s)
#  hosts: vbox-si-asm
#  user: vagrant
#  become: yes
#  roles:
#     - oradb-manage-pdb
#     - oradb-manage-tablespace
#     - oradb-manage-parameters
#     - oradb-manage-redo
#     - oradb-manage-roles
#     - oradb-manage-users
#     - oradb-manage-grants
#     - oradb-manage-services

**Comment by akerrai** [comment]
I was using the vbox-si-asm-install.yml:

---
- name: Host configuration
  hosts: vbox-si-asm
  user: root
  become: yes
  roles:
     - common
     - orahost
     - orahost-storage

- name: Oracle Grid Infrastructure installation
  hosts: vbox-si-asm
  user: root
  become: yes
  roles:
     - oraswgi-install

- name: ASM Diskgroup configuration
  hosts: vbox-si-asm
  user: root
  become: yes
  roles:
      - oraasm-createdg

- name: Database Server Installation & Database Creation
  hosts: vbox-si-asm
  user: root
  become: yes
  roles:
      - oraswdb-install
      - oradb-create

**Comment by oravirt** [comment]
ok - weird. 
You should do a `git pull` to get the latest changes. It does not look like that anymore

**Comment by akerrai** [comment]
Okay thanks, I will pull down again but made some changes to allow it to work with our environment builds.

I didn't think about the deprecation, so as always apologies for my time-wasting through lack of working Ansible 101.

**Comment by oravirt** [comment]
No problems, happy to help

**Comment by kiruba87** [comment]
I took having the same issue while creating the database using oradb-create roles. I am trying to create database alone. DB has created but it fails in post activities. 

"msg": "AnsibleUndefinedVariable: 'dbh' is undefined"}

Below is my playbook,

[root@18cpocanbu ansible-oracle-master]# cat single-instance-dbcreation.yml
---


 - name: Database Server Installation & Database Creation
   hosts: 104.45.3.126
   user: oracle
   become: yes
   roles:
      - oradb-create

Any help would highly appreciated.

**Comment by kiruba87** [comment]
TASK [oradb-create : Add dotprofile (2)] *******************************************************************************************************************************
failed: [104.45.3.126] (item=[{u'oracle_init_params': u'', u'oracle_db_type': u'SI', u'service_name': u'clouddb', u'listener_name': u'LISTENER', u'storage_type': u'FS', u'home': u'db1', u'is_container': True, u'redolog_size_in_mb': 100, u'num_pdbs': 1, u'pdb_prefix': u'pdb', u'oracle_db_name': u'clouddb', u'state': u'present', u'oracle_edition': u'EE', u'oracle_db_mem_totalmb': 1024, u'oracle_database_type': u'MULTIPURPOSE', u'oracle_version_db': u'12.2.0.1'}, {'stderr_lines': [], 'ansible_loop_var': u'item', u'end': u'2019-08-03 10:28:10.190750', u'stderr': u'', u'stdout': u'clouddb', u'changed': False, 'failed': False, u'delta': u'0:00:00.040710', u'cmd': u'ps -ef | grep -w "ora_pmon_clouddb" |grep -v grep | sed \'s/^.*pmon_//g\'', 'item': {u'oracle_init_params': u'', u'oracle_db_type': u'SI', u'service_name': u'clouddb', u'listener_name': u'LISTENER', u'storage_type': u'FS', u'home': u'db1', u'is_container': True, u'redolog_size_in_mb': 100, u'num_pdbs': 1, u'pdb_prefix': u'pdb', u'oracle_db_name': u'clouddb', u'state': u'present', u'oracle_edition': u'EE', u'oracle_db_mem_totalmb': 1024, u'oracle_database_type': u'MULTIPURPOSE', u'oracle_version_db': u'12.2.0.1'}, u'rc': 0, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'strip_empty_ends': True, u'_raw_params': u'ps -ef | grep -w "ora_pmon_clouddb" |grep -v grep | sed \'s/^.*pmon_//g\'', u'removes': None, u'argv': None, u'creates': None, u'chdir': None, u'stdin_add_newline': True, u'stdin': None}}, 'stdout_lines': [u'clouddb'], u'start': u'2019-08-03 10:28:10.150040'}]) => {"ansible_loop_var": "item", "changed": false, "item": [{"home": "db1", "is_container": true, "listener_name": "LISTENER", "num_pdbs": 1, "oracle_database_type": "MULTIPURPOSE", "oracle_db_mem_totalmb": 1024, "oracle_db_name": "clouddb", "oracle_db_type": "SI", "oracle_edition": "EE", "oracle_init_params": "", "oracle_version_db": "12.2.0.1", "pdb_prefix": "pdb", "redolog_size_in_mb": 100, "service_name": "clouddb", "state": "present", "storage_type": "FS"}, {"ansible_loop_var": "item", "changed": false, "cmd": "ps -ef | grep -w \"ora_pmon_clouddb\" |grep -v grep | sed 's/^.*pmon_//g'", "delta": "0:00:00.040710", "end": "2019-08-03 10:28:10.190750", "failed": false, "invocation": {"module_args": {"_raw_params": "ps -ef | grep -w \"ora_pmon_clouddb\" |grep -v grep | sed 's/^.*pmon_//g'", "_uses_shell": true, "argv": null, "chdir": null, "creates": null, "executable": null, "removes": null, "stdin": null, "stdin_add_newline": true, "strip_empty_ends": true, "warn": true}}, "item": {"home": "db1", "is_container": true, "listener_name": "LISTENER", "num_pdbs": 1, "oracle_database_type": "MULTIPURPOSE", "oracle_db_mem_totalmb": 1024, "oracle_db_name": "clouddb", "oracle_db_type": "SI", "oracle_edition": "EE", "oracle_init_params": "", "oracle_version_db": "12.2.0.1", "pdb_prefix": "pdb", "redolog_size_in_mb": 100, "service_name": "clouddb", "state": "present", "storage_type": "FS"}, "rc": 0, "start": "2019-08-03 10:28:10.150040", "stderr": "", "stderr_lines": [], "stdout": "clouddb", "stdout_lines": ["clouddb"]}], "msg": "AnsibleUndefinedVariable: 'dbh' is undefined"}

PLAY RECAP *************************************************************************************************************************************************************
104.45.3.126               : ok=9    changed=4    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0

**Comment by oravirt** [comment]
Hi,
In the future, It's better if you create a new issue instead of using a closed issue.

But, you should swap out the `oradb-create` role (which is deprecated)  and use `oradb-manage-db` instead.
