### ISSUE TITLE
do opatch before root.sh in role oraswgi-install for Oracle GI 11.2 Installation on RHEL 7

### ISSUE THREAD

**Issue by honglei** [oravirt/ansible-oracle#80]
I've met the following problem : [Oracle GI 11.2 Installation on RHEL 7 – Error: ohasd failed to start the Clusterware.](https://fatdba.com/2016/01/06/oracle-gi-11-2-installation-on-rhel-7-error-ohasd-failed-to-start-failed-to-start-the-clusterware-last-20-lines-of-the-alert-log-follow-ohasd-failed-to-start-at-u01app11-2-0gridcrsinstallr/)

**Comment by oravirt** [comment]
Yeah, applying patches before finalizing an installation is something I'm looking into. It is nontrivial for < 12.2 GI, but I'll fix it eventually.
