### ISSUE TITLE
MIssing port in oradb-manage-users, oradb-manage-roles...

### ISSUE THREAD

**Issue by Rendanic** [oravirt/ansible-oracle#87]
The administration with the new roles is not possible with a listener on port <> 1521.
The reason is a missing parameter in the mapping to the library modules.

The port could be read from listener_port in oracle_databases.

Should I creae a pull request for the fix?

**Comment by oravirt** [comment]
No - there is no need for a PR. 
I'm fixing some other things as well with those new roles (e.g removing the hardcoded ansible_hostname as the host for cx_Oracle), and this is one of the other things I'm fixing.

Good catch though!

**Comment by Rendanic** [comment]
fixed by #92
