### ISSUE TITLE
Bug in ASMCA | Create script to build asm-diskgroups

### ISSUE THREAD

**Issue by Rendanic** [oravirt/ansible-oracle#9]
There is a big danger in creating diskgroups with normal/high redundancy when using more then 2 disks in 2 Storage systems. Most people wants to use 2 failure groups for a normal redundancy diskgroup, but ASM will create a failure group for each disk when no failure group name is used while creating the diskgroup or adding a disk.
When 1 storage system fails, more then 1 failure group is missing and the diskgroup is immediatly dismounted and cannot mounted until a minimum of number Failgroups-1 is availible in normal redundancy.

I add the failgroup-parameter to asm_diskgroups for normal/high redundancy. Existing configurations are not affected but keep in mind that most admins use a wrong diskgroup configuration.

Example:
  asm_diskgroups:
    - diskgroup: grid
      properties:
        - {redundancy: normal, ausize: 4}
      attributes:
        - {name: 'compatible.rdbms', value: 11.2.0.4.0}
        - {name: 'compatible.asm', value: 12.1.0.2.0}
      disk:
        - {device: /dev/sdc, asmlabel: grid01, failgroup: fg1}
        - {device: /dev/sdc, asmlabel: grid01, failgroup: fg2}

**Comment by oravirt** [comment]
Yeah I know. This was not written with 2 storagesystems in mind, I just needed something that could keep my CRS diskgroup in normal redundancy at that time.
I've been meaning to do this properly ever since but never gotten around to it, mostly because we don't mirror between 2 arrays.
Thanks for fixing it!

**Comment by Rendanic** [comment]
#10
