### ISSUE TITLE
oradb-manage-parameters: Problem with oracle_pdbs when pdb not existing

### ISSUE THREAD

**Issue by Rendanic** [oravirt/ansible-oracle#93]
I ran into the following problem:
Define an init.ora-Parameter for the cdb. As an addition define a parameter in oracle_pdbs.
You get a problem, when the parameter in cdb is needed for the pdb.

This will not set the parameter for the pdb, but an important parameter for the creation of the pdb itself could be missind:
- oradb-manage-pdb
- oradb-manage-parameter

This creates an error, becauso the pdb is missing:
- oradb-manage-parameter
- oradb-manage-pdb

Solution:
Set the parameter directly in oracle_database outside of oradb-manage-parameter.
Important:
We need to make sure, that the old behavior for setting parameters in oracle_database cannot be removed until the problem with oradb-manage-parameter is solved.

Kind Regards
Thorsten Bruhns

**Comment by oravirt** [comment]
I see the problem, and this can be done today. However, I want to change a few things in the `oracle_db` module first before fixing this.

Out of curiosity, what parameters did you need before the pdb was created?

**Comment by oravirt** [comment]
8aa981d should fix this. If any parameter(s) are defined in the `init_parameters` list in `oracle_databases` they will be applied during initial DB/CDB creation.
For an example look in https://github.com/oravirt/ansible-oracle/blob/master/group_vars/vbox-si-asm/databases.yml

**Comment by Rendanic** [comment]
This issue has been fixed and it is working.

Thanks a lot for the fast solution!
