### ISSUE TITLE
asmlibsupport_rpm:  Add support for CentOS 7

### ISSUE THREAD

**Issue by enlightenalpha** [oravirt/ansible-oracle#94]
Location: roles/orahost/defaults/main.yml
asmlibsupport_rpm is based on conditional using ansible_distribution == 'RedHat'

This fails on CentOS.  We needed to replace with:
ansible_distribution_file_variety == 'RedHat'

**Comment by oravirt** [comment]
Thanks for pointing this out.
I will probably change this to `ansible_os_family`, since that's what is used everywhere else to differentiate between Suse & RedHat.

**Comment by oravirt** [comment]
Fixed with 0fa35a768af8b69341316348687309343ff6088e

**Comment by Rendanic** [comment]
looks fixed
