### ISSUE TITLE
Parted fails without -s option

### ISSUE THREAD

**Issue by enlightenalpha** [oravirt/ansible-oracle#95]
Branch: Master
Target OS: CentOS Linux release 7.5.1804
Role: roles/orahost/tasks/main.yml
Task: name: filesystem | Create partition and pv
Problem:  Task fails due to user confirmation prompt.  Adding -s resolves:

`shell:  parted -a optimal -s {{ item.1.device }} "mklabel gpt mkpart primary 1 -1" `

**Comment by oravirt** [comment]
Not sure what this is, as I can't reproduce it. 

However, I've added the -s flag (0fa35a768af8b69341316348687309343ff6088e)

**Comment by enlightenalpha** [comment]
Confirmed that this works.  Thank you.
