### ISSUE TITLE
cx_oracle module import fails due to restrictive umask

### ISSUE THREAD

**Issue by enlightenalpha** [oravirt/ansible-oracle#97]
/roles/cxoracle/tasks/main.yml

We needed to add a more forgiving umask for the cx_oracle install task, otherwise only the root user can import the module.  

pip: name=cx_oracle state=present extra_args="{{ extra_args }}" **umask=0022**

**Comment by oravirt** [comment]
Fixed with 344325bc6b7a35376c0e32a3e79f29c5bf0c476d.

I've never seen issues with this, so I'm leaving the default as is, but I've made it configurable

e.g
`cx_oracle_umask: 0022`

The task does:
`umask: {{ cx_oracle_umask | default(omit) }}`

**Comment by enlightenalpha** [comment]
Confirmed that this works, however please note that when defining this parameter the value will need to be quoted:

cx_oracle_umask: "0022"
